(lex.add.entry '(T_IY_Z nil (((t iy z) 0))
(lex.add.entry '(L_EH_P_T nil (((l eh p t) 0))
(lex.add.entry '(EY_T nil (((ey t) 0))
(lex.add.entry '(T_IY_S nil (((t iy s) 0))
(lex.add.entry '(D_AH_N_L_N_S nil (((d ah n l n s) 0))
(lex.add.entry '(K_OW nil (((k ow) 0))
(lex.add.entry '(T_IY_T nil (((t iy t) 0))
(lex.add.entry '(T_IY_K nil (((t iy k) 0))
(lex.add.entry '(T_IY_N nil (((t iy n) 0))
(lex.add.entry '(T_IY_L nil (((t iy l) 0))
(lex.add.entry '(T_IY_M nil (((t iy m) 0))
(lex.add.entry '(EY_K nil (((ey k) 0))
(lex.add.entry '(EY_N nil (((ey n) 0))
(lex.add.entry '(T_IY_D nil (((t iy d) 0))
(lex.add.entry '(EY_L nil (((ey l) 0))
(lex.add.entry '(T_AH_K nil (((t ah k) 0))
(lex.add.entry '(B_OW_N nil (((b ow n) 0))
(lex.add.entry '(T_AH_N nil (((t ah n) 0))
(lex.add.entry '(K_IY_CH_T nil (((k iy ch t) 0))
(lex.add.entry '(T_AH_L nil (((t ah l) 0))
(lex.add.entry '(S_AH_P_L nil (((s ah p l) 0))
(lex.add.entry '(T_AH_D nil (((t ah d) 0))
(lex.add.entry '(K_IY_CH_D nil (((k iy ch d) 0))
(lex.add.entry '(S_IY_K nil (((s iy k) 0))
(lex.add.entry '(T_AH_R nil (((t ah r) 0))
(lex.add.entry '(T_AH_P nil (((t ah p) 0))
(lex.add.entry '(S_IY_N nil (((s iy n) 0))
(lex.add.entry '(S_IY_M nil (((s iy m) 0))
(lex.add.entry '(T_AH_T nil (((t ah t) 0))
(lex.add.entry '(F_IH nil (((f ih) 0))
(lex.add.entry '(L_EH_L_N_L nil (((l eh l n l) 0))
(lex.add.entry '(F_IY nil (((f iy) 0))
(lex.add.entry '(T_AY_S nil (((t ay s) 0))
(lex.add.entry '(T_Y_EH_L nil (((t y eh l) 0))
(lex.add.entry '(T_Y_EH_N nil (((t y eh n) 0))
(lex.add.entry '(P_AY_N nil (((p ay n) 0))
(lex.add.entry '(D_EH_L_N_T_K nil (((d eh l n t k) 0))
(lex.add.entry '(T_AY_D nil (((t ay d) 0))
(lex.add.entry '(T_Y_EH_R nil (((t y eh r) 0))
(lex.add.entry '(T_AY_N nil (((t ay n) 0))
(lex.add.entry '(T_AY_L nil (((t ay l) 0))
(lex.add.entry '(T_AY_M nil (((t ay m) 0))
(lex.add.entry '(S_K_L_AH nil (((s k l ah) 0))
(lex.add.entry '(T_IY_G nil (((t iy g) 0))
(lex.add.entry '(EY_M nil (((ey m) 0))
(lex.add.entry '(HH_IY_L_M_S nil (((hh iy l m s) 0))
(lex.add.entry '(B_OW_L nil (((b ow l) 0))
(lex.add.entry '(R_AY_N_T_L_N_M nil (((r ay n t l n m) 0))
(lex.add.entry '(P_OW_L_S nil (((p ow l s) 0))
(lex.add.entry '(T_AH_M nil (((t ah m) 0))
(lex.add.entry '(D_OW_K_T nil (((d ow k t) 0))
(lex.add.entry '(S_IY_T nil (((s iy t) 0))
(lex.add.entry '(F_EH_M nil (((f eh m) 0))
(lex.add.entry '(F_EH_N nil (((f eh n) 0))
(lex.add.entry '(D_OW_K_N nil (((d ow k n) 0))
(lex.add.entry '(G_AH_SH_L nil (((g ah sh l) 0))
(lex.add.entry '(R_AH_M nil (((r ah m) 0))
(lex.add.entry '(R_AH_L nil (((r ah l) 0))
(lex.add.entry '(R_AH_N nil (((r ah n) 0))
(lex.add.entry '(R_AH_P nil (((r ah p) 0))
(lex.add.entry '(P_EH_L_N nil (((p eh l n) 0))
(lex.add.entry '(R_AH_R nil (((r ah r) 0))
(lex.add.entry '(D_AH_M_K nil (((d ah m k) 0))
(lex.add.entry '(K_AH_L_N_T nil (((k ah l n t) 0))
(lex.add.entry '(M_UW_P nil (((m uw p) 0))
(lex.add.entry '(M_UW_K nil (((m uw k) 0))
(lex.add.entry '(T_AH_N_T_L_P_K nil (((t ah n t l p k) 0))
(lex.add.entry '(B_L_IH nil (((b l ih) 0))
(lex.add.entry '(T_AH_S nil (((t ah s) 0))
(lex.add.entry '(B_L_IY_L_P nil (((b l iy l p) 0))
(lex.add.entry '(IY_T_T nil (((iy t t) 0))
(lex.add.entry '(B_L_IY nil (((b l iy) 0))
(lex.add.entry '(D_OW nil (((d ow) 0))
(lex.add.entry '(B_Y_AH_L_K nil (((b y ah l k) 0))
(lex.add.entry '(D_OY nil (((d oy) 0))
(lex.add.entry '(Z_AH_L_M nil (((z ah l m) 0))
(lex.add.entry '(Z_AH_N_T nil (((z ah n t) 0))
(lex.add.entry '(B_AH_L_P_T nil (((b ah l p t) 0))
(lex.add.entry '(D_AH_N_T nil (((d ah n t) 0))
(lex.add.entry '(Z_AH_N_L nil (((z ah n l) 0))
(lex.add.entry '(B_AH_L_P_K nil (((b ah l p k) 0))
(lex.add.entry '(D_AH_N_L nil (((d ah n l) 0))
(lex.add.entry '(D_AH_N_M nil (((d ah n m) 0))
(lex.add.entry '(Z_AH_L_S nil (((z ah l s) 0))
(lex.add.entry '(Z_AH_L_P nil (((z ah l p) 0))
(lex.add.entry '(D_AH_L_M nil (((d ah l m) 0))
(lex.add.entry '(IY_N_T nil (((iy n t) 0))
(lex.add.entry '(D_AH_L_K nil (((d ah l k) 0))
(lex.add.entry '(D_AH_R_T nil (((d ah r t) 0))
(lex.add.entry '(K_AO_F nil (((k ao f) 0))
(lex.add.entry '(D_AH_L_Z nil (((d ah l z) 0))
(lex.add.entry '(D_AH_L_T nil (((d ah l t) 0))
(lex.add.entry '(K_AO_S nil (((k ao s) 0))
(lex.add.entry '(D_AH_L_P nil (((d ah l p) 0))
(lex.add.entry '(D_AH_L_S nil (((d ah l s) 0))
(lex.add.entry '(L_Y_EH_L nil (((l y eh l) 0))
(lex.add.entry '(S_K_AY nil (((s k ay) 0))
(lex.add.entry '(G_L_IY nil (((g l iy) 0))
(lex.add.entry '(L_Y_EH_T nil (((l y eh t) 0))
(lex.add.entry '(L_Y_EH_R nil (((l y eh r) 0))
(lex.add.entry '(B_AH_L_T_D nil (((b ah l t d) 0))
(lex.add.entry '(L_IY_CH_T nil (((l iy ch t) 0))
(lex.add.entry '(N_IH_T nil (((n ih t) 0))
(lex.add.entry '(B_AH_L_T_S nil (((b ah l t s) 0))
(lex.add.entry '(N_AH_N_SH nil (((n ah n sh) 0))
(lex.add.entry '(N_AH_P_L nil (((n ah p l) 0))
(lex.add.entry '(T_AO_K nil (((t ao k) 0))
(lex.add.entry '(B_L_AY_T nil (((b l ay t) 0))
(lex.add.entry '(R_IY_CH_T nil (((r iy ch t) 0))
(lex.add.entry '(T_AO_R nil (((t ao r) 0))
(lex.add.entry '(T_AO_S nil (((t ao s) 0))
(lex.add.entry '(B_L_AY_N nil (((b l ay n) 0))
(lex.add.entry '(N_AH_N_L nil (((n ah n l) 0))
(lex.add.entry '(F_AH_P nil (((f ah p) 0))
(lex.add.entry '(F_AH_R nil (((f ah r) 0))
(lex.add.entry '(D_AH_P_L nil (((d ah p l) 0))
(lex.add.entry '(F_AH_M nil (((f ah m) 0))
(lex.add.entry '(F_AH_L nil (((f ah l) 0))
(lex.add.entry '(N_AH_N_S nil (((n ah n s) 0))
(lex.add.entry '(N_AH_N_T nil (((n ah n t) 0))
(lex.add.entry '(F_AH_K nil (((f ah k) 0))
(lex.add.entry '(CH_AY nil (((ch ay) 0))
(lex.add.entry '(CH_AH nil (((ch ah) 0))
(lex.add.entry '(CH_AO nil (((ch ao) 0))
(lex.add.entry '(B_L_EH_N nil (((b l eh n) 0))
(lex.add.entry '(B_L_EH_K nil (((b l eh k) 0))
(lex.add.entry '(P_L_IY_S nil (((p l iy s) 0))
(lex.add.entry '(B_AH_NG nil (((b ah ng) 0))
(lex.add.entry '(K_L_IY nil (((k l iy) 0))
(lex.add.entry '(M_IY_N_L_N nil (((m iy n l n) 0))
(lex.add.entry '(HH_AH_N_L_N_T nil (((hh ah n l n t) 0))
(lex.add.entry '(K_L_IH nil (((k l ih) 0))
(lex.add.entry '(K_AH_R_K_T nil (((k ah r k t) 0))
(lex.add.entry '(B_IY_CH_T nil (((b iy ch t) 0))
(lex.add.entry '(B_AH_L_N_T nil (((b ah l n t) 0))
(lex.add.entry '(T_Y_AO_N_L nil (((t y ao n l) 0))
(lex.add.entry '(B_L_IY_N nil (((b l iy n) 0))
(lex.add.entry '(S_IY nil (((s iy) 0))
(lex.add.entry '(T_EY_T_K nil (((t ey t k) 0))
(lex.add.entry '(S_IH nil (((s ih) 0))
(lex.add.entry '(K_L_AY_L_N_P_L nil (((k l ay l n p l) 0))
(lex.add.entry '(K_AH_L_P_T nil (((k ah l p t) 0))
(lex.add.entry '(L_AY_N_T_K nil (((l ay n t k) 0))
(lex.add.entry '(D_AH_N_L_N nil (((d ah n l n) 0))
(lex.add.entry '(D_AH_N_L_T nil (((d ah n l t) 0))
(lex.add.entry '(B_AH_T_S nil (((b ah t s) 0))
(lex.add.entry '(K_AH_L_P_K nil (((k ah l p k) 0))
(lex.add.entry '(AH_N_L_T_N nil (((ah n l t n) 0))
(lex.add.entry '(R_AH nil (((r ah) 0))
(lex.add.entry '(S_M_AH_S nil (((s m ah s) 0))
(lex.add.entry '(M_UW nil (((m uw) 0))
(lex.add.entry '(P_EH_T_S nil (((p eh t s) 0))
(lex.add.entry '(HH_IY_N nil (((hh iy n) 0))
(lex.add.entry '(HH_IY_M nil (((hh iy m) 0))
(lex.add.entry '(HH_IY_L nil (((hh iy l) 0))
(lex.add.entry '(L_Y_AH_L nil (((l y ah l) 0))
(lex.add.entry '(L_Y_AH_N nil (((l y ah n) 0))
(lex.add.entry '(HH_IY_T nil (((hh iy t) 0))
(lex.add.entry '(HH_IY_S nil (((hh iy s) 0))
(lex.add.entry '(HH_IY_R nil (((hh iy r) 0))
(lex.add.entry '(S_M_AH_N nil (((s m ah n) 0))
(lex.add.entry '(S_P_L_AH_N nil (((s p l ah n) 0))
(lex.add.entry '(P_L_IY nil (((p l iy) 0))
(lex.add.entry '(K_IY_T_K nil (((k iy t k) 0))
(lex.add.entry '(P_OW nil (((p ow) 0))
(lex.add.entry '(P_L_IH nil (((p l ih) 0))
(lex.add.entry '(Z_AH_L_S_T nil (((z ah l s t) 0))
(lex.add.entry '(HH_AY_N_T nil (((hh ay n t) 0))
(lex.add.entry '(S_T_EH nil (((s t eh) 0))
(lex.add.entry '(L_AH_D_M nil (((l ah d m) 0))
(lex.add.entry '(Z_AH_R_D nil (((z ah r d) 0))
(lex.add.entry '(L_AH_D_K nil (((l ah d k) 0))
(lex.add.entry '(S_T_EY nil (((s t ey) 0))
(lex.add.entry '(Z_AH_R_N nil (((z ah r n) 0))
(lex.add.entry '(T_Y_AH_L_P nil (((t y ah l p) 0))
(lex.add.entry '(T_Y_AH_L_T nil (((t y ah l t) 0))
(lex.add.entry '(D_EH_NG_K_T nil (((d eh ng k t) 0))
(lex.add.entry '(M_AY_N_T_K nil (((m ay n t k) 0))
(lex.add.entry '(T_Y_AH_L_K nil (((t y ah l k) 0))
(lex.add.entry '(T_Y_AH_L_N nil (((t y ah l n) 0))
(lex.add.entry '(Z_AH_N_L_N nil (((z ah n l n) 0))
(lex.add.entry '(K_Y_OW_N nil (((k y ow n) 0))
(lex.add.entry '(S_M_IY nil (((s m iy) 0))
(lex.add.entry '(N_Y_AO nil (((n y ao) 0))
(lex.add.entry '(N_Y_AH nil (((n y ah) 0))
(lex.add.entry '(HH_EY_K nil (((hh ey k) 0))
(lex.add.entry '(HH_EY_N nil (((hh ey n) 0))
(lex.add.entry '(D_EH_NG nil (((d eh ng) 0))
(lex.add.entry '(R_EH_T nil (((r eh t) 0))
(lex.add.entry '(D_AH_NG_K nil (((d ah ng k) 0))
(lex.add.entry '(R_EH_S nil (((r eh s) 0))
(lex.add.entry '(R_EH_R nil (((r eh r) 0))
(lex.add.entry '(R_EH_M nil (((r eh m) 0))
(lex.add.entry '(R_EH_N nil (((r eh n) 0))
(lex.add.entry '(B_L_AH_N nil (((b l ah n) 0))
(lex.add.entry '(M_IY nil (((m iy) 0))
(lex.add.entry '(K_R_AY nil (((k r ay) 0))
(lex.add.entry '(T_EH_M_M nil (((t eh m m) 0))
(lex.add.entry '(N_L nil (((n l) 0))
(lex.add.entry '(CH_AY_N_T nil (((ch ay n t) 0))
(lex.add.entry '(G_AH_T_S nil (((g ah t s) 0))
(lex.add.entry '(T_AH_L_N_T_L nil (((t ah l n t l) 0))
(lex.add.entry '(T_Y_EH_D nil (((t y eh d) 0))
(lex.add.entry '(G_AH_N_T nil (((g ah n t) 0))
(lex.add.entry '(G_AH_N_S nil (((g ah n s) 0))
(lex.add.entry '(F_EH nil (((f eh) 0))
(lex.add.entry '(K_AY_M_T nil (((k ay m t) 0))
(lex.add.entry '(G_AH_N_L nil (((g ah n l) 0))
(lex.add.entry '(Y_OW nil (((y ow) 0))
(lex.add.entry '(Z_EH_NG nil (((z eh ng) 0))
(lex.add.entry '(AY_N_T_P nil (((ay n t p) 0))
(lex.add.entry '(AY_N_T_S nil (((ay n t s) 0))
(lex.add.entry '(B_AY_L_D nil (((b ay l d) 0))
(lex.add.entry '(AY_N_T_K nil (((ay n t k) 0))
(lex.add.entry '(UW_N_T_S nil (((uw n t s) 0))
(lex.add.entry '(D_AH_L_S_T nil (((d ah l s t) 0))
(lex.add.entry '(S_T_AH_R nil (((s t ah r) 0))
(lex.add.entry '(L_IY_N_T nil (((l iy n t) 0))
(lex.add.entry '(S_AY_L_M nil (((s ay l m) 0))
(lex.add.entry '(S_AY_L_N nil (((s ay l n) 0))
(lex.add.entry '(Z_OW_N_T nil (((z ow n t) 0))
(lex.add.entry '(Z_AH_NG nil (((z ah ng) 0))
(lex.add.entry '(EY_T_S nil (((ey t s) 0))
(lex.add.entry '(Z_OW_L nil (((z ow l) 0))
(lex.add.entry '(Z_OW_N nil (((z ow n) 0))
(lex.add.entry '(T_Y_AH_R nil (((t y ah r) 0))
(lex.add.entry '(Z_OW_T nil (((z ow t) 0))
(lex.add.entry '(S_IY_NG nil (((s iy ng) 0))
(lex.add.entry '(T_Y_AH_L nil (((t y ah l) 0))
(lex.add.entry '(T_Y_AH_N nil (((t y ah n) 0))
(lex.add.entry '(N_IY_S_T nil (((n iy s t) 0))
(lex.add.entry '(AH_N_SH nil (((ah n sh) 0))
(lex.add.entry '(T_AH_L_N_P_L nil (((t ah l n p l) 0))
(lex.add.entry '(CH nil (((ch) 0))
(lex.add.entry '(G_AH_L_P nil (((g ah l p) 0))
(lex.add.entry '(G_AH_L_S nil (((g ah l s) 0))
(lex.add.entry '(G_AH_L_T nil (((g ah l t) 0))
(lex.add.entry '(G_AH_L_K nil (((g ah l k) 0))
(lex.add.entry '(G_AH_L_M nil (((g ah l m) 0))
(lex.add.entry '(G_AH_L_N nil (((g ah l n) 0))
(lex.add.entry '(Z_OW_P_L nil (((z ow p l) 0))
(lex.add.entry '(B_L_IY_CH nil (((b l iy ch) 0))
(lex.add.entry '(S_AY_N_T nil (((s ay n t) 0))
(lex.add.entry '(K_AO_K_T_S nil (((k ao k t s) 0))
(lex.add.entry '(HH_AY_T_P_L nil (((hh ay t p l) 0))
(lex.add.entry '(Z_OW_L_K nil (((z ow l k) 0))
(lex.add.entry '(F_EH_R nil (((f eh r) 0))
(lex.add.entry '(D_Y_AH_L nil (((d y ah l) 0))
(lex.add.entry '(D_Y_AH_N nil (((d y ah n) 0))
(lex.add.entry '(M_AH_L_N nil (((m ah l n) 0))
(lex.add.entry '(M_AH_L_M nil (((m ah l m) 0))
(lex.add.entry '(M_AH_L_K nil (((m ah l k) 0))
(lex.add.entry '(M_AH_L_T nil (((m ah l t) 0))
(lex.add.entry '(M_AH_L_S nil (((m ah l s) 0))
(lex.add.entry '(M_AH_L_P nil (((m ah l p) 0))
(lex.add.entry '(D_IY_T_K_L nil (((d iy t k l) 0))
(lex.add.entry '(M_AH_N_L nil (((m ah n l) 0))
(lex.add.entry '(T_Y_EH_N_T_K nil (((t y eh n t k) 0))
(lex.add.entry '(M_AH_N_T nil (((m ah n t) 0))
(lex.add.entry '(D_AH_L_P_K nil (((d ah l p k) 0))
(lex.add.entry '(G_L_OW nil (((g l ow) 0))
(lex.add.entry '(N_Y_EH_L_N nil (((n y eh l n) 0))
(lex.add.entry '(N_Y_EH_L_D nil (((n y eh l d) 0))
(lex.add.entry '(D_AH nil (((d ah) 0))
(lex.add.entry '(T_Y_AH_L_P_K nil (((t y ah l p k) 0))
(lex.add.entry '(T_EH_S_T nil (((t eh s t) 0))
(lex.add.entry '(N_UW_N_T_K nil (((n uw n t k) 0))
(lex.add.entry '(T_AH_L_M_P_T nil (((t ah l m p t) 0))
(lex.add.entry '(S_T_AH_T nil (((s t ah t) 0))
(lex.add.entry '(G_R_IY_S_T nil (((g r iy s t) 0))
(lex.add.entry '(S_T_AH_N nil (((s t ah n) 0))
(lex.add.entry '(S_T_AH_L nil (((s t ah l) 0))
(lex.add.entry '(T_Y_AH_L_K_T nil (((t y ah l k t) 0))
(lex.add.entry '(L_AH_R_K nil (((l ah r k) 0))
(lex.add.entry '(T_IY_CH nil (((t iy ch) 0))
(lex.add.entry '(HH_EH_R nil (((hh eh r) 0))
(lex.add.entry '(F_AO_R_N nil (((f ao r n) 0))
(lex.add.entry '(K_OW_NG nil (((k ow ng) 0))
(lex.add.entry '(Z_IY_N_D nil (((z iy n d) 0))
(lex.add.entry '(EY_N_HH_R nil (((ey n hh r) 0))
(lex.add.entry '(M_AY_N_L_P nil (((m ay n l p) 0))
(lex.add.entry '(S_T_AY_N nil (((s t ay n) 0))
(lex.add.entry '(B_AH_K_T nil (((b ah k t) 0))
(lex.add.entry '(R_AH_T nil (((r ah t) 0))
(lex.add.entry '(D_AH_N_SH nil (((d ah n sh) 0))
(lex.add.entry '(T_AH_R_K_T nil (((t ah r k t) 0))
(lex.add.entry '(G_L_IY_T nil (((g l iy t) 0))
(lex.add.entry '(P_L_IY_CH nil (((p l iy ch) 0))
(lex.add.entry '(L_AH_D_K_T nil (((l ah d k t) 0))
(lex.add.entry '(L_Y_EH_T_T nil (((l y eh t t) 0))
(lex.add.entry '(M_AH_R_K nil (((m ah r k) 0))
(lex.add.entry '(L_Y_EH_N_T nil (((l y eh n t) 0))
(lex.add.entry '(T_IY_N_T nil (((t iy n t) 0))
(lex.add.entry '(HH_AY_T nil (((hh ay t) 0))
(lex.add.entry '(HH_AY_N nil (((hh ay n) 0))
(lex.add.entry '(HH_AY_M nil (((hh ay m) 0))
(lex.add.entry '(HH_AY_L nil (((hh ay l) 0))
(lex.add.entry '(L_Y_EH_N_D nil (((l y eh n d) 0))
(lex.add.entry '(D_EH_R_G_L_K nil (((d eh r g l k) 0))
(lex.add.entry '(T_IY_N_K nil (((t iy n k) 0))
(lex.add.entry '(HH_AY_D nil (((hh ay d) 0))
(lex.add.entry '(T_IY_N_L nil (((t iy n l) 0))
(lex.add.entry '(S_T_EH_S nil (((s t eh s) 0))
(lex.add.entry '(S_T_EH_R nil (((s t eh r) 0))
(lex.add.entry '(S_T_EH_N nil (((s t eh n) 0))
(lex.add.entry '(S_T_EH_M nil (((s t eh m) 0))
(lex.add.entry '(Y_EH_L nil (((y eh l) 0))
(lex.add.entry '(Y_EH_N nil (((y eh n) 0))
(lex.add.entry '(Y_EH_R nil (((y eh r) 0))
(lex.add.entry '(HH_EY nil (((hh ey) 0))
(lex.add.entry '(HH_EH nil (((hh eh) 0))
(lex.add.entry '(N_UW_N_T nil (((n uw n t) 0))
(lex.add.entry '(K_OW_L_K_T nil (((k ow l k t) 0))
(lex.add.entry '(EY_L_N nil (((ey l n) 0))
(lex.add.entry '(G_AH_NG_K nil (((g ah ng k) 0))
(lex.add.entry '(S_EH_N_D nil (((s eh n d) 0))
(lex.add.entry '(EY_N_T nil (((ey n t) 0))
(lex.add.entry '(N_EH_R_T_S nil (((n eh r t s) 0))
(lex.add.entry '(EY_N_L nil (((ey n l) 0))
(lex.add.entry '(HH_EH_R_K_T nil (((hh eh r k t) 0))
(lex.add.entry '(S_AH_L_S_T nil (((s ah l s t) 0))
(lex.add.entry '(N_Y_EH_M nil (((n y eh m) 0))
(lex.add.entry '(N_Y_EH_L nil (((n y eh l) 0))
(lex.add.entry '(EY_G_L nil (((ey g l) 0))
(lex.add.entry '(T_IY_L_M nil (((t iy l m) 0))
(lex.add.entry '(T_IY_L_N nil (((t iy l n) 0))
(lex.add.entry '(S_M_IY_L_K nil (((s m iy l k) 0))
(lex.add.entry '(T_OW nil (((t ow) 0))
(lex.add.entry '(S_OW nil (((s ow) 0))
(lex.add.entry '(D_Y_AH_L_N nil (((d y ah l n) 0))
(lex.add.entry '(D_Y_AH_L_S nil (((d y ah l s) 0))
(lex.add.entry '(Y_AH nil (((y ah) 0))
(lex.add.entry '(N_EH_N_T_S nil (((n eh n t s) 0))
(lex.add.entry '(Y_EH_NG nil (((y eh ng) 0))
(lex.add.entry '(K_L_EH nil (((k l eh) 0))
(lex.add.entry '(L_Y_EH_D nil (((l y eh d) 0))
(lex.add.entry '(B_EH nil (((b eh) 0))
(lex.add.entry '(S_T_UW nil (((s t uw) 0))
(lex.add.entry '(D_EH_R_T_S nil (((d eh r t s) 0))
(lex.add.entry '(B_EY nil (((b ey) 0))
(lex.add.entry '(P_L_EH nil (((p l eh) 0))
(lex.add.entry '(P_IH nil (((p ih) 0))
(lex.add.entry '(L_AH_P_T_K nil (((l ah p t k) 0))
(lex.add.entry '(T_IY_K_T nil (((t iy k t) 0))
(lex.add.entry '(K_L_AY_CH nil (((k l ay ch) 0))
(lex.add.entry '(M_OW_N nil (((m ow n) 0))
(lex.add.entry '(T_IY_N_L_N_T nil (((t iy n l n t) 0))
(lex.add.entry '(M_OW_K nil (((m ow k) 0))
(lex.add.entry '(HH_AH_NG_K nil (((hh ah ng k) 0))
(lex.add.entry '(HH_AH_NG_L nil (((hh ah ng l) 0))
(lex.add.entry '(N_OW_T_S nil (((n ow t s) 0))
(lex.add.entry '(T_AH_R_D nil (((t ah r d) 0))
(lex.add.entry '(N_EH nil (((n eh) 0))
(lex.add.entry '(HH_AH_R nil (((hh ah r) 0))
(lex.add.entry '(V_IY_N nil (((v iy n) 0))
(lex.add.entry '(HH_AH_F nil (((hh ah f) 0))
(lex.add.entry '(HH_AH_D nil (((hh ah d) 0))
(lex.add.entry '(N_EY nil (((n ey) 0))
(lex.add.entry '(HH_AH_B nil (((hh ah b) 0))
(lex.add.entry '(HH_AH_N nil (((hh ah n) 0))
(lex.add.entry '(HH_AH_L nil (((hh ah l) 0))
(lex.add.entry '(HH_AH_M nil (((hh ah m) 0))
(lex.add.entry '(M_IY_L_K nil (((m iy l k) 0))
(lex.add.entry '(V_AY_L nil (((v ay l) 0))
(lex.add.entry '(K_AH_R_P nil (((k ah r p) 0))
(lex.add.entry '(M_AY_L_D nil (((m ay l d) 0))
(lex.add.entry '(T_Y_EH nil (((t y eh) 0))
(lex.add.entry '(S_T_EH_T_S_T_S nil (((s t eh t s t s) 0))
(lex.add.entry '(N_OW_K_N nil (((n ow k n) 0))
(lex.add.entry '(B_AO_K nil (((b ao k) 0))
(lex.add.entry '(T_Y_AH_L_N_T nil (((t y ah l n t) 0))
(lex.add.entry '(N_Y_AH_R nil (((n y ah r) 0))
(lex.add.entry '(L_AY_N_T nil (((l ay n t) 0))
(lex.add.entry '(N_Y_AH_N nil (((n y ah n) 0))
(lex.add.entry '(N_Y_AH_M nil (((n y ah m) 0))
(lex.add.entry '(N_Y_AH_L nil (((n y ah l) 0))
(lex.add.entry '(N_EH_NG nil (((n eh ng) 0))
(lex.add.entry '(AH_N_M nil (((ah n m) 0))
(lex.add.entry '(AH_N_L nil (((ah n l) 0))
(lex.add.entry '(B_AH_T nil (((b ah t) 0))
(lex.add.entry '(T_Y_EH_N_T_L_N nil (((t y eh n t l n) 0))
(lex.add.entry '(AH_N_D nil (((ah n d) 0))
(lex.add.entry '(M_AY_N_T nil (((m ay n t) 0))
(lex.add.entry '(L_AH_N_T_K_T nil (((l ah n t k t) 0))
(lex.add.entry '(M_AY_N_L nil (((m ay n l) 0))
(lex.add.entry '(B_AH_G nil (((b ah g) 0))
(lex.add.entry '(M_IY_NG nil (((m iy ng) 0))
(lex.add.entry '(B_AH_K nil (((b ah k) 0))
(lex.add.entry '(AH_N_T nil (((ah n t) 0))
(lex.add.entry '(B_AH_M nil (((b ah m) 0))
(lex.add.entry '(B_AH_L nil (((b ah l) 0))
(lex.add.entry '(IY_CH_T nil (((iy ch t) 0))
(lex.add.entry '(B_AH_N nil (((b ah n) 0))
(lex.add.entry '(L_OY nil (((l oy) 0))
(lex.add.entry '(L_OW nil (((l ow) 0))
(lex.add.entry '(T_IY_NG nil (((t iy ng) 0))
(lex.add.entry '(D_EH_N_T_L_T nil (((d eh n t l t) 0))
(lex.add.entry '(D_IH_K nil (((d ih k) 0))
(lex.add.entry '(T_AY_N_T nil (((t ay n t) 0))
(lex.add.entry '(T_AY_N_K nil (((t ay n k) 0))
(lex.add.entry '(S_AH_N_L_N nil (((s ah n l n) 0))
(lex.add.entry '(SH_L_AH nil (((sh l ah) 0))
(lex.add.entry '(T_AY_N_M nil (((t ay n m) 0))
(lex.add.entry '(D_IH_T nil (((d ih t) 0))
(lex.add.entry '(N_EH_N_T_P_T nil (((n eh n t p t) 0))
(lex.add.entry '(D_EH_N_T_L_N nil (((d eh n t l n) 0))
(lex.add.entry '(T_AY_N_D nil (((t ay n d) 0))
(lex.add.entry '(T_AY_L_M nil (((t ay l m) 0))
(lex.add.entry '(T_AY_L_N nil (((t ay l n) 0))
(lex.add.entry '(N_IY_N_L_N nil (((n iy n l n) 0))
(lex.add.entry '(T_AY_L_K nil (((t ay l k) 0))
(lex.add.entry '(T_AY_L_D nil (((t ay l d) 0))
(lex.add.entry '(S_AH_R_P_M_S nil (((s ah r p m s) 0))
(lex.add.entry '(T_AY_L_T nil (((t ay l t) 0))
(lex.add.entry '(L_AH_N_SH nil (((l ah n sh) 0))
(lex.add.entry '(T_AY_L_P nil (((t ay l p) 0))
(lex.add.entry '(G_IH nil (((g ih) 0))
(lex.add.entry '(L_AY nil (((l ay) 0))
(lex.add.entry '(G_IY nil (((g iy) 0))
(lex.add.entry '(L_AO nil (((l ao) 0))
(lex.add.entry '(L_AH nil (((l ah) 0))
(lex.add.entry '(S_OW_K nil (((s ow k) 0))
(lex.add.entry '(S_OW_N nil (((s ow n) 0))
(lex.add.entry '(B_L_AY_N_S nil (((b l ay n s) 0))
(lex.add.entry '(G_L_IY_NG nil (((g l iy ng) 0))
(lex.add.entry '(T_AO_K_N nil (((t ao k n) 0))
(lex.add.entry '(S_EH_P_T nil (((s eh p t) 0))
(lex.add.entry '(L_S nil (((l s) 0))
(lex.add.entry '(D_IY_CH nil (((d iy ch) 0))
(lex.add.entry '(B_EH_N nil (((b eh n) 0))
(lex.add.entry '(B_EH_S nil (((b eh s) 0))
(lex.add.entry '(B_EH_R nil (((b eh r) 0))
(lex.add.entry '(D_AH_L_N nil (((d ah l n) 0))
(lex.add.entry '(D_AH_L_K_T nil (((d ah l k t) 0))
(lex.add.entry '(L_EH_N nil (((l eh n) 0))
(lex.add.entry '(L_EH_M nil (((l eh m) 0))
(lex.add.entry '(L_EH_L nil (((l eh l) 0))
(lex.add.entry '(L_EH_K nil (((l eh k) 0))
(lex.add.entry '(N_IY_N_T_K nil (((n iy n t k) 0))
(lex.add.entry '(Z_OW nil (((z ow) 0))
(lex.add.entry '(S_EH_R_K nil (((s eh r k) 0))
(lex.add.entry '(L_EH_T nil (((l eh t) 0))
(lex.add.entry '(L_EH_S nil (((l eh s) 0))
(lex.add.entry '(L_EH_R nil (((l eh r) 0))
(lex.add.entry '(L_EH_P nil (((l eh p) 0))
(lex.add.entry '(SH_OW nil (((sh ow) 0))
(lex.add.entry '(V_EH_S_T nil (((v eh s t) 0))
(lex.add.entry '(G_L_AY_N nil (((g l ay n) 0))
(lex.add.entry '(D_AH_L_N_T_K nil (((d ah l n t k) 0))
(lex.add.entry '(G_L_AY_M nil (((g l ay m) 0))
(lex.add.entry '(G_AY_L nil (((g ay l) 0))
(lex.add.entry '(G_L_AY_P nil (((g l ay p) 0))
(lex.add.entry '(T_AH_L_K_T nil (((t ah l k t) 0))
(lex.add.entry '(N_OW_B_L nil (((n ow b l) 0))
(lex.add.entry '(N_UW_NG nil (((n uw ng) 0))
(lex.add.entry '(B_IY_N_T nil (((b iy n t) 0))
(lex.add.entry '(P_OW_R_K nil (((p ow r k) 0))
(lex.add.entry '(B_IY_N_K nil (((b iy n k) 0))
(lex.add.entry '(B_IY_N_D nil (((b iy n d) 0))
(lex.add.entry '(B_IY_L_P nil (((b iy l p) 0))
(lex.add.entry '(B_L_EH nil (((b l eh) 0))
(lex.add.entry '(D_EH_NG_K nil (((d eh ng k) 0))
(lex.add.entry '(D_EH_NG_M nil (((d eh ng m) 0))
(lex.add.entry '(G_EH_S nil (((g eh s) 0))
(lex.add.entry '(G_EH_P nil (((g eh p) 0))
(lex.add.entry '(G_EH_T nil (((g eh t) 0))
(lex.add.entry '(G_EH_N nil (((g eh n) 0))
(lex.add.entry '(G_EH_L nil (((g eh l) 0))
(lex.add.entry '(D_EH_NG_S nil (((d eh ng s) 0))
(lex.add.entry '(D_EH_NG_T nil (((d eh ng t) 0))
(lex.add.entry '(L_AH_G nil (((l ah g) 0))
(lex.add.entry '(B_AY_T_N nil (((b ay t n) 0))
(lex.add.entry '(L_AH_D nil (((l ah d) 0))
(lex.add.entry '(L_AH_K nil (((l ah k) 0))
(lex.add.entry '(L_AH_N nil (((l ah n) 0))
(lex.add.entry '(L_AH_M nil (((l ah m) 0))
(lex.add.entry '(D_IY_F_T_K nil (((d iy f t k) 0))
(lex.add.entry '(L_AH_S nil (((l ah s) 0))
(lex.add.entry '(L_AH_R nil (((l ah r) 0))
(lex.add.entry '(L_AH_P nil (((l ah p) 0))
(lex.add.entry '(L_AH_T nil (((l ah t) 0))
(lex.add.entry '(B_AY_T_T nil (((b ay t t) 0))
(lex.add.entry '(N_EH_N_D nil (((n eh n d) 0))
(lex.add.entry '(S_K_OW nil (((s k ow) 0))
(lex.add.entry '(N_EH_N_T nil (((n eh n t) 0))
(lex.add.entry '(R_AH_L_S_T nil (((r ah l s t) 0))
(lex.add.entry '(K_AH_NG nil (((k ah ng) 0))
(lex.add.entry '(N_EH_N_S nil (((n eh n s) 0))
(lex.add.entry '(G_AH_P nil (((g ah p) 0))
(lex.add.entry '(Z_IY_CH nil (((z iy ch) 0))
(lex.add.entry '(P_OW_L_T nil (((p ow l t) 0))
(lex.add.entry '(P_OW_L_P nil (((p ow l p) 0))
(lex.add.entry '(N_AH_M_K_N_T nil (((n ah m k n t) 0))
(lex.add.entry '(P_OW_L_M nil (((p ow l m) 0))
(lex.add.entry '(P_OW_L_N nil (((p ow l n) 0))
(lex.add.entry '(P_OW_L_K nil (((p ow l k) 0))
(lex.add.entry '(D_UW nil (((d uw) 0))
(lex.add.entry '(G_IY_N nil (((g iy n) 0))
(lex.add.entry '(G_IY_L nil (((g iy l) 0))
(lex.add.entry '(V_IY nil (((v iy) 0))
(lex.add.entry '(Z_AY nil (((z ay) 0))
(lex.add.entry '(L_UW_NG nil (((l uw ng) 0))
(lex.add.entry '(R_AH_L_N_T nil (((r ah l n t) 0))
(lex.add.entry '(N_UW_N nil (((n uw n) 0))
(lex.add.entry '(Z_AH nil (((z ah) 0))
(lex.add.entry '(Z_AO nil (((z ao) 0))
(lex.add.entry '(M_EY_N nil (((m ey n) 0))
(lex.add.entry '(N_IY_NG nil (((n iy ng) 0))
(lex.add.entry '(R_AH_L_T_D nil (((r ah l t d) 0))
(lex.add.entry '(N_AH_N_K_L nil (((n ah n k l) 0))
(lex.add.entry '(V_AH_L_T nil (((v ah l t) 0))
(lex.add.entry '(Z_EY_K nil (((z ey k) 0))
(lex.add.entry '(S_T_AY nil (((s t ay) 0))
(lex.add.entry '(N_Y_EH_N nil (((n y eh n) 0))
(lex.add.entry '(T_AH_L_S_T nil (((t ah l s t) 0))
(lex.add.entry '(SH_L_AH_N_T nil (((sh l ah n t) 0))
(lex.add.entry '(S_EH_N_T nil (((s eh n t) 0))
(lex.add.entry '(T_Y_UW_K nil (((t y uw k) 0))
(lex.add.entry '(L_IY_L_T nil (((l iy l t) 0))
(lex.add.entry '(T_Y_UW_D nil (((t y uw d) 0))
(lex.add.entry '(SH_L_AH_N_D nil (((sh l ah n d) 0))
(lex.add.entry '(L_IY_L_N nil (((l iy l n) 0))
(lex.add.entry '(K_Y_EH nil (((k y eh) 0))
(lex.add.entry '(M_IY_CH nil (((m iy ch) 0))
(lex.add.entry '(D_EH_D nil (((d eh d) 0))
(lex.add.entry '(D_EH_N nil (((d eh n) 0))
(lex.add.entry '(D_EH_M nil (((d eh m) 0))
(lex.add.entry '(D_EH_L nil (((d eh l) 0))
(lex.add.entry '(D_EH_K nil (((d eh k) 0))
(lex.add.entry '(D_EH_T nil (((d eh t) 0))
(lex.add.entry '(D_EH_S nil (((d eh s) 0))
(lex.add.entry '(D_EH_R nil (((d eh r) 0))
(lex.add.entry '(D_EH_P nil (((d eh p) 0))
(lex.add.entry '(S_T_AO nil (((s t ao) 0))
(lex.add.entry '(G_Y_AH_N nil (((g y ah n) 0))
(lex.add.entry '(R_AO_P_L nil (((r ao p l) 0))
(lex.add.entry '(SH_EH_NG nil (((sh eh ng) 0))
(lex.add.entry '(S_N_AH nil (((s n ah) 0))
(lex.add.entry '(K_L_AY_P nil (((k l ay p) 0))
(lex.add.entry '(SH_L_AH_N_T_K nil (((sh l ah n t k) 0))
(lex.add.entry '(T_AH_N_L_T nil (((t ah n l t) 0))
(lex.add.entry '(T_AY nil (((t ay) 0))
(lex.add.entry '(T_IY_L_T nil (((t iy l t) 0))
(lex.add.entry '(P_L_AH_N nil (((p l ah n) 0))
(lex.add.entry '(CH_AH_N nil (((ch ah n) 0))
(lex.add.entry '(T_AO nil (((t ao) 0))
(lex.add.entry '(T_AH nil (((t ah) 0))
(lex.add.entry '(P_L_AH_S nil (((p l ah s) 0))
(lex.add.entry '(T_AH_N_L_N nil (((t ah n l n) 0))
(lex.add.entry '(AH_R nil (((ah r) 0))
(lex.add.entry '(T_UW_N_T nil (((t uw n t) 0))
(lex.add.entry '(T_EH_R_K_T nil (((t eh r k t) 0))
(lex.add.entry '(R_EH nil (((r eh) 0))
(lex.add.entry '(M_IY_CH_T nil (((m iy ch t) 0))
(lex.add.entry '(S_AY_T nil (((s ay t) 0))
(lex.add.entry '(S_AY_N nil (((s ay n) 0))
(lex.add.entry '(S_F_AH nil (((s f ah) 0))
(lex.add.entry '(Z_EH_R_P_T nil (((z eh r p t) 0))
(lex.add.entry '(N_EH_N_T_K nil (((n eh n t k) 0))
(lex.add.entry '(R_AY_N_T nil (((r ay n t) 0))
(lex.add.entry '(G_AH_N nil (((g ah n) 0))
(lex.add.entry '(G_AH_L nil (((g ah l) 0))
(lex.add.entry '(G_AH_M nil (((g ah m) 0))
(lex.add.entry '(L_EH_CH nil (((l eh ch) 0))
(lex.add.entry '(G_AH_T nil (((g ah t) 0))
(lex.add.entry '(G_AH_R nil (((g ah r) 0))
(lex.add.entry '(T_Y_UW_NG nil (((t y uw ng) 0))
(lex.add.entry '(R_EH_NG nil (((r eh ng) 0))
(lex.add.entry '(M_EY_M nil (((m ey m) 0))
(lex.add.entry '(N_UW_M nil (((n uw m) 0))
(lex.add.entry '(B_IH nil (((b ih) 0))
(lex.add.entry '(HH_OY_L nil (((hh oy l) 0))
(lex.add.entry '(L_AY_S_T nil (((l ay s t) 0))
(lex.add.entry '(B_IY nil (((b iy) 0))
(lex.add.entry '(S_T_AH nil (((s t ah) 0))
(lex.add.entry '(M_EY_T nil (((m ey t) 0))
(lex.add.entry '(L_AH_N_T_T nil (((l ah n t t) 0))
(lex.add.entry '(CH_AH_M nil (((ch ah m) 0))
(lex.add.entry '(L_AH_N_T_P nil (((l ah n t p) 0))
(lex.add.entry '(L_AH_N_T_S nil (((l ah n t s) 0))
(lex.add.entry '(S_T_AH_L_K nil (((s t ah l k) 0))
(lex.add.entry '(N_AH_L_N_T_L nil (((n ah l n t l) 0))
(lex.add.entry '(AH_S nil (((ah s) 0))
(lex.add.entry '(AH_P nil (((ah p) 0))
(lex.add.entry '(CH_AH_F nil (((ch ah f) 0))
(lex.add.entry '(AH_N nil (((ah n) 0))
(lex.add.entry '(AH_L nil (((ah l) 0))
(lex.add.entry '(AH_M nil (((ah m) 0))
(lex.add.entry '(AH_K nil (((ah k) 0))
(lex.add.entry '(CH_AH_R nil (((ch ah r) 0))
(lex.add.entry '(L_AH_N_T_K nil (((l ah n t k) 0))
(lex.add.entry '(M_EH_R nil (((m eh r) 0))
(lex.add.entry '(D_IY_NG nil (((d iy ng) 0))
(lex.add.entry '(M_EH_D nil (((m eh d) 0))
(lex.add.entry '(M_EH_N nil (((m eh n) 0))
(lex.add.entry '(AY_N_T_K_N_T nil (((ay n t k n t) 0))
(lex.add.entry '(Y_AO nil (((y ao) 0))
(lex.add.entry '(T_Y_UW nil (((t y uw) 0))
(lex.add.entry '(HH_AH_R_K nil (((hh ah r k) 0))
(lex.add.entry '(M_IY_T nil (((m iy t) 0))
(lex.add.entry '(M_IY_S nil (((m iy s) 0))
(lex.add.entry '(HH_AH_L_M nil (((hh ah l m) 0))
(lex.add.entry '(D_IY_CH_T nil (((d iy ch t) 0))
(lex.add.entry '(N_OW_L_K_T nil (((n ow l k t) 0))
(lex.add.entry '(M_IY_L nil (((m iy l) 0))
(lex.add.entry '(M_IY_N nil (((m iy n) 0))
(lex.add.entry '(B_IY_K nil (((b iy k) 0))
(lex.add.entry '(L_Y_OW_K nil (((l y ow k) 0))
(lex.add.entry '(Z_IY_NG nil (((z iy ng) 0))
(lex.add.entry '(AY_T nil (((ay t) 0))
(lex.add.entry '(HH_AH_T_M nil (((hh ah t m) 0))
(lex.add.entry '(AY_N nil (((ay n) 0))
(lex.add.entry '(B_IY_CH_T_N nil (((b iy ch t n) 0))
(lex.add.entry '(S_AH_K nil (((s ah k) 0))
(lex.add.entry '(S_AH_N nil (((s ah n) 0))
(lex.add.entry '(S_AH_L nil (((s ah l) 0))
(lex.add.entry '(S_AH_M nil (((s ah m) 0))
(lex.add.entry '(S_AH_R nil (((s ah r) 0))
(lex.add.entry '(S_AH_S nil (((s ah s) 0))
(lex.add.entry '(S_AH_P nil (((s ah p) 0))
(lex.add.entry '(K_IY_CH nil (((k iy ch) 0))
(lex.add.entry '(S_AH_T nil (((s ah t) 0))
(lex.add.entry '(L_EH_N_T nil (((l eh n t) 0))
(lex.add.entry '(K_AY nil (((k ay) 0))
(lex.add.entry '(EH_L_P nil (((eh l p) 0))
(lex.add.entry '(F_AY nil (((f ay) 0))
(lex.add.entry '(EH_L_N nil (((eh l n) 0))
(lex.add.entry '(S_T_AH_R_K nil (((s t ah r k) 0))
(lex.add.entry '(F_AO nil (((f ao) 0))
(lex.add.entry '(K_AO nil (((k ao) 0))
(lex.add.entry '(HH_AH_N_T_K nil (((hh ah n t k) 0))
(lex.add.entry '(P_L_IY_NG nil (((p l iy ng) 0))
(lex.add.entry '(F_AH nil (((f ah) 0))
(lex.add.entry '(L_UW nil (((l uw) 0))
(lex.add.entry '(IY nil (((iy) 0))
(lex.add.entry '(IH nil (((ih) 0))
(lex.add.entry '(T_AH_N_L nil (((t ah n l) 0))
(lex.add.entry '(T_AH_N_M nil (((t ah n m) 0))
(lex.add.entry '(T_AH_L_T nil (((t ah l t) 0))
(lex.add.entry '(T_AY_N_T_L_N nil (((t ay n t l n) 0))
(lex.add.entry '(V_AY_L_N nil (((v ay l n) 0))
(lex.add.entry '(S_AO_S nil (((s ao s) 0))
(lex.add.entry '(K_IY_S nil (((k iy s) 0))
(lex.add.entry '(T_AH_L_P nil (((t ah l p) 0))
(lex.add.entry '(K_IY_T nil (((k iy t) 0))
(lex.add.entry '(N_AH_N_P nil (((n ah n p) 0))
(lex.add.entry '(L_UW_N_T_P nil (((l uw n t p) 0))
(lex.add.entry '(S_AO_D nil (((s ao d) 0))
(lex.add.entry '(S_AO_F nil (((s ao f) 0))
(lex.add.entry '(S_AO_K nil (((s ao k) 0))
(lex.add.entry '(K_IY_G nil (((k iy g) 0))
(lex.add.entry '(N_AO_F nil (((n ao f) 0))
(lex.add.entry '(L_AY_CH nil (((l ay ch) 0))
(lex.add.entry '(F_AH_N nil (((f ah n) 0))
(lex.add.entry '(K_L_IY_N nil (((k l iy n) 0))
(lex.add.entry '(D_EH_S_T nil (((d eh s t) 0))
(lex.add.entry '(N_AO_N nil (((n ao n) 0))
(lex.add.entry '(N_AO_M nil (((n ao m) 0))
(lex.add.entry '(N_AO_K nil (((n ao k) 0))
(lex.add.entry '(N_AO_S nil (((n ao s) 0))
(lex.add.entry '(K_L_IY_T nil (((k l iy t) 0))
(lex.add.entry '(D_IY_T_K nil (((d iy t k) 0))
(lex.add.entry '(R_AH_N_L nil (((r ah n l) 0))
(lex.add.entry '(EH_N_D nil (((eh n d) 0))
(lex.add.entry '(D_IY_T_T nil (((d iy t t) 0))
(lex.add.entry '(EH_N_T nil (((eh n t) 0))
(lex.add.entry '(CH_EH_N_S nil (((ch eh n s) 0))
(lex.add.entry '(EH_R_P nil (((eh r p) 0))
(lex.add.entry '(EH_R_K nil (((eh r k) 0))
(lex.add.entry '(D_IY_N_D nil (((d iy n d) 0))
(lex.add.entry '(B_OY nil (((b oy) 0))
(lex.add.entry '(M_AO_N_T nil (((m ao n t) 0))
(lex.add.entry '(D_IY_N_L nil (((d iy n l) 0))
(lex.add.entry '(S_T_AY_N_T nil (((s t ay n t) 0))
(lex.add.entry '(Y_OW_N nil (((y ow n) 0))
(lex.add.entry '(D_IY_L_L nil (((d iy l l) 0))
(lex.add.entry '(SH_IY nil (((sh iy) 0))
(lex.add.entry '(S_K_L_IY nil (((s k l iy) 0))
(lex.add.entry '(S_T_IY_CH nil (((s t iy ch) 0))
(lex.add.entry '(AH nil (((ah) 0))
(lex.add.entry '(EH_CH nil (((eh ch) 0))
(lex.add.entry '(R_IY_N nil (((r iy n) 0))
(lex.add.entry '(D_EY_T_K nil (((d ey t k) 0))
(lex.add.entry '(D_EH nil (((d eh) 0))
(lex.add.entry '(HH_AH_L_P nil (((hh ah l p) 0))
(lex.add.entry '(HH_AH_L_T nil (((hh ah l t) 0))
(lex.add.entry '(EH_R nil (((eh r) 0))
(lex.add.entry '(EH_S nil (((eh s) 0))
(lex.add.entry '(HH_AH_N_D nil (((hh ah n d) 0))
(lex.add.entry '(EH_T nil (((eh t) 0))
(lex.add.entry '(EH_K nil (((eh k) 0))
(lex.add.entry '(M_AH_NG nil (((m ah ng) 0))
(lex.add.entry '(EH_L nil (((eh l) 0))
(lex.add.entry '(EH_M nil (((eh m) 0))
(lex.add.entry '(G_AH_NG_T_S nil (((g ah ng t s) 0))
(lex.add.entry '(HH_AH_N_T nil (((hh ah n t) 0))
(lex.add.entry '(OW_K nil (((ow k) 0))
(lex.add.entry '(G_R_AH nil (((g r ah) 0))
(lex.add.entry '(HH_AH_L_N nil (((hh ah l n) 0))
(lex.add.entry '(S_K_IY nil (((s k iy) 0))
(lex.add.entry '(Y_AH_L_N nil (((y ah l n) 0))
(lex.add.entry '(B_AH_R nil (((b ah r) 0))
(lex.add.entry '(T_IH_T nil (((t ih t) 0))
(lex.add.entry '(T_EH_L_N_T nil (((t eh l n t) 0))
(lex.add.entry '(T_Y_AH_NG nil (((t y ah ng) 0))
(lex.add.entry '(Y_AH_L_S nil (((y ah l s) 0))
(lex.add.entry '(Y_AH_L_P nil (((y ah l p) 0))
(lex.add.entry '(G_L_OW_M nil (((g l ow m) 0))
(lex.add.entry '(D_EH_L_N_D nil (((d eh l n d) 0))
(lex.add.entry '(N_EH_N_L_N_T nil (((n eh n l n t) 0))
(lex.add.entry '(IY_NG nil (((iy ng) 0))
(lex.add.entry '(D_EH_L_N_T nil (((d eh l n t) 0))
(lex.add.entry '(T_AH_NG nil (((t ah ng) 0))
(lex.add.entry '(V_IY_N_T nil (((v iy n t) 0))
(lex.add.entry '(L_IY_CH nil (((l iy ch) 0))
(lex.add.entry '(T_IY_CH_T nil (((t iy ch t) 0))
(lex.add.entry '(N_IY_CH_T_S nil (((n iy ch t s) 0))
(lex.add.entry '(T_AH_L_M nil (((t ah l m) 0))
(lex.add.entry '(EY_S nil (((ey s) 0))
(lex.add.entry '(N_EH_L_P nil (((n eh l p) 0))
(lex.add.entry '(L_Y_EH nil (((l y eh) 0))
(lex.add.entry '(D_AH_T_S nil (((d ah t s) 0))
(lex.add.entry '(S_AH_R_T nil (((s ah r t) 0))
(lex.add.entry '(S_AH_R_D nil (((s ah r d) 0))
(lex.add.entry '(K_OW_N_T_L nil (((k ow n t l) 0))
(lex.add.entry '(AY_N_T nil (((ay n t) 0))
(lex.add.entry '(N_AH_L_P_K nil (((n ah l p k) 0))
(lex.add.entry '(AY_N_D nil (((ay n d) 0))
(lex.add.entry '(M_AH_T nil (((m ah t) 0))
(lex.add.entry '(M_AH_P nil (((m ah p) 0))
(lex.add.entry '(M_AH_R nil (((m ah r) 0))
(lex.add.entry '(M_AH_S nil (((m ah s) 0))
(lex.add.entry '(HH_AH_T nil (((hh ah t) 0))
(lex.add.entry '(M_AH_L nil (((m ah l) 0))
(lex.add.entry '(M_AH_M nil (((m ah m) 0))
(lex.add.entry '(M_AH_N nil (((m ah n) 0))
(lex.add.entry '(D_IY_K_L nil (((d iy k l) 0))
(lex.add.entry '(M_AH_K nil (((m ah k) 0))
(lex.add.entry '(D_AH_S_T nil (((d ah s t) 0))
(lex.add.entry '(HH_AH nil (((hh ah) 0))
(lex.add.entry '(HH_AO nil (((hh ao) 0))
(lex.add.entry '(IY_M_T nil (((iy m t) 0))
(lex.add.entry '(V_AY_T_P nil (((v ay t p) 0))
(lex.add.entry '(HH_AY nil (((hh ay) 0))
(lex.add.entry '(K_L_IY_L_N_S nil (((k l iy l n s) 0))
(lex.add.entry '(S_EH_N nil (((s eh n) 0))
(lex.add.entry '(S_EH_K nil (((s eh k) 0))
(lex.add.entry '(S_AH_N_L nil (((s ah n l) 0))
(lex.add.entry '(S_AH_L_T nil (((s ah l t) 0))
(lex.add.entry '(S_EH_D nil (((s eh d) 0))
(lex.add.entry '(S_AH_L_P nil (((s ah l p) 0))
(lex.add.entry '(S_AH_L_S nil (((s ah l s) 0))
(lex.add.entry '(S_AH_L_M nil (((s ah l m) 0))
(lex.add.entry '(S_AH_L_N nil (((s ah l n) 0))
(lex.add.entry '(S_AH_L_K nil (((s ah l k) 0))
(lex.add.entry '(S_AH_L_D nil (((s ah l d) 0))
(lex.add.entry '(S_EH_R nil (((s eh r) 0))
(lex.add.entry '(S_EH_P nil (((s eh p) 0))
(lex.add.entry '(S_AH_N_T nil (((s ah n t) 0))
(lex.add.entry '(M_AY_N nil (((m ay n) 0))
(lex.add.entry '(M_AY_D nil (((m ay d) 0))
(lex.add.entry '(M_AY_T nil (((m ay t) 0))
(lex.add.entry '(V_EH nil (((v eh) 0))
(lex.add.entry '(V_OW_L nil (((v ow l) 0))
(lex.add.entry '(D_EH_L_N nil (((d eh l n) 0))
(lex.add.entry '(P_AH_R_S_P nil (((p ah r s p) 0))
(lex.add.entry '(K_L_AH nil (((k l ah) 0))
(lex.add.entry '(P_L_AH nil (((p l ah) 0))
(lex.add.entry '(K_L_AY nil (((k l ay) 0))
(lex.add.entry '(L_UW_M nil (((l uw m) 0))
(lex.add.entry '(K_OW_N_L_N nil (((k ow n l n) 0))
(lex.add.entry '(S_AY nil (((s ay) 0))
(lex.add.entry '(L_UW_K nil (((l uw k) 0))
(lex.add.entry '(K_AH_R nil (((k ah r) 0))
(lex.add.entry '(K_AH_S nil (((k ah s) 0))
(lex.add.entry '(K_AH_P nil (((k ah p) 0))
(lex.add.entry '(K_AH_T nil (((k ah t) 0))
(lex.add.entry '(K_AH_K nil (((k ah k) 0))
(lex.add.entry '(S_AO nil (((s ao) 0))
(lex.add.entry '(K_AH_N nil (((k ah n) 0))
(lex.add.entry '(S_AH nil (((s ah) 0))
(lex.add.entry '(K_AH_L nil (((k ah l) 0))
(lex.add.entry '(K_AH_M nil (((k ah m) 0))
(lex.add.entry '(N_AH_L_N_T nil (((n ah l n t) 0))
(lex.add.entry '(HH_IY_CH_T nil (((hh iy ch t) 0))
(lex.add.entry '(N_AH_L_N_D nil (((n ah l n d) 0))
(lex.add.entry '(N_AH_L_N_K nil (((n ah l n k) 0))
(lex.add.entry '(S_P_OW nil (((s p ow) 0))
(lex.add.entry '(N_AY nil (((n ay) 0))
(lex.add.entry '(S_T_OW nil (((s t ow) 0))
(lex.add.entry '(R_IY nil (((r iy) 0))
(lex.add.entry '(T_AH_R_K_L nil (((t ah r k l) 0))
(lex.add.entry '(N_AO nil (((n ao) 0))
(lex.add.entry '(N_AH nil (((n ah) 0))
(lex.add.entry '(R_IH nil (((r ih) 0))
(lex.add.entry '(B_OW nil (((b ow) 0))
(lex.add.entry '(B_AH_N_L_N nil (((b ah n l n) 0))
(lex.add.entry '(B_AH_N_L_M nil (((b ah n l m) 0))
(lex.add.entry '(B_AH_N_L_T nil (((b ah n l t) 0))
(lex.add.entry '(SH_AH_N nil (((sh ah n) 0))
(lex.add.entry '(IY_N nil (((iy n) 0))
(lex.add.entry '(IY_M nil (((iy m) 0))
(lex.add.entry '(IY_L nil (((iy l) 0))
(lex.add.entry '(HH_IY_NG nil (((hh iy ng) 0))
(lex.add.entry '(K_EH_N nil (((k eh n) 0))
(lex.add.entry '(K_EH_R nil (((k eh r) 0))
(lex.add.entry '(IY_T nil (((iy t) 0))
(lex.add.entry '(IY_S nil (((iy s) 0))
(lex.add.entry '(CH_AH_N_L_N nil (((ch ah n l n) 0))
(lex.add.entry '(EH_NG nil (((eh ng) 0))
(lex.add.entry '(B_IY_CH nil (((b iy ch) 0))
(lex.add.entry '(N_Y_AH_R_Z nil (((n y ah r z) 0))
(lex.add.entry '(N_Y_AH_R_T nil (((n y ah r t) 0))
(lex.add.entry '(K_AH_L_S_T nil (((k ah l s t) 0))
(lex.add.entry '(P_EH_S_T nil (((p eh s t) 0))
(lex.add.entry '(N_Y_AH_R_D nil (((n y ah r d) 0))
(lex.add.entry '(L_Y_AO_N nil (((l y ao n) 0))
(lex.add.entry '(D_OW_R_K nil (((d ow r k) 0))
(lex.add.entry '(N_AH_L_P nil (((n ah l p) 0))
(lex.add.entry '(T_Y_AH nil (((t y ah) 0))
(lex.add.entry '(T_Y_AO nil (((t y ao) 0))
(lex.add.entry '(G_L_AH_NG nil (((g l ah ng) 0))
(lex.add.entry '(N_OW nil (((n ow) 0))
(lex.add.entry '(M_OW nil (((m ow) 0))
(lex.add.entry '(M_OY nil (((m oy) 0))
(lex.add.entry '(T_IY_N_L_N nil (((t iy n l n) 0))
(lex.add.entry '(N_OY nil (((n oy) 0))
(lex.add.entry '(SH_AH_L_N_T nil (((sh ah l n t) 0))
(lex.add.entry '(HH_IY_L_N_T nil (((hh iy l n t) 0))
(lex.add.entry '(L nil (((l) 0))
(lex.add.entry '(L_EH nil (((l eh) 0))
(lex.add.entry '(G_EH nil (((g eh) 0))
(lex.add.entry '(R_AY_N nil (((r ay n) 0))
(lex.add.entry '(N_Y_AO_N_T nil (((n y ao n t) 0))
(lex.add.entry '(K_AH nil (((k ah) 0))
(lex.add.entry '(Z_OW_N_T_L nil (((z ow n t l) 0))
(lex.add.entry '(G_EH_N_T nil (((g eh n t) 0))
(lex.add.entry '(L_Y_AH_L_S nil (((l y ah l s) 0))
(lex.add.entry '(L_Y_AH_L_P nil (((l y ah l p) 0))
(lex.add.entry '(HH_AY_T_T nil (((hh ay t t) 0))
(lex.add.entry '(L_Y_AH_L_T nil (((l y ah l t) 0))
(lex.add.entry '(IY_S_T nil (((iy s t) 0))
(lex.add.entry '(T_AY_T_S_T nil (((t ay t s t) 0))
(lex.add.entry '(G_EH_L_P nil (((g eh l p) 0))
(lex.add.entry '(K_AH_P_L_N nil (((k ah p l n) 0))
(lex.add.entry '(HH_AY_L_D nil (((hh ay l d) 0))
(lex.add.entry '(EH nil (((eh) 0))
(lex.add.entry '(S_IY_S nil (((s iy s) 0))
(lex.add.entry '(S_N_IY_N nil (((s n iy n) 0))
(lex.add.entry '(EY nil (((ey) 0))
(lex.add.entry '(N_AH_B_L nil (((n ah b l) 0))
(lex.add.entry '(S_K_AY_N_T nil (((s k ay n t) 0))
(lex.add.entry '(K_OW_L_T nil (((k ow l t) 0))
(lex.add.entry '(N_AH_L_D nil (((n ah l d) 0))
(lex.add.entry '(K_OW_L_P nil (((k ow l p) 0))
(lex.add.entry '(K_OW_L_S nil (((k ow l s) 0))
(lex.add.entry '(N_AH_L_N nil (((n ah l n) 0))
(lex.add.entry '(N_AH_L_M nil (((n ah l m) 0))
(lex.add.entry '(N_AH_L_K nil (((n ah l k) 0))
(lex.add.entry '(K_OW_N_L nil (((k ow n l) 0))
(lex.add.entry '(N_AH_L_T nil (((n ah l t) 0))
(lex.add.entry '(N_AH_L_S nil (((n ah l s) 0))
(lex.add.entry '(K_OW_N_T nil (((k ow n t) 0))
(lex.add.entry '(S_UW_D nil (((s uw d) 0))
(lex.add.entry '(K_OW_L_N nil (((k ow l n) 0))
(lex.add.entry '(N_AH_L_Z nil (((n ah l z) 0))
(lex.add.entry '(K_OW_L_K nil (((k ow l k) 0))
(lex.add.entry '(B_AH_L_S_T nil (((b ah l s t) 0))
(lex.add.entry '(D_OW_N nil (((d ow n) 0))
(lex.add.entry '(D_OW_L nil (((d ow l) 0))
(lex.add.entry '(D_OW_K nil (((d ow k) 0))
(lex.add.entry '(D_OW_R nil (((d ow r) 0))
(lex.add.entry '(HH_IY_L_M nil (((hh iy l m) 0))
(lex.add.entry '(HH_IY_L_N nil (((hh iy l n) 0))
(lex.add.entry '(HH_IY_L_D nil (((hh iy l d) 0))
(lex.add.entry '(Y_EH_L_P nil (((y eh l p) 0))
(lex.add.entry '(K_IY_N_S nil (((k iy n s) 0))
(lex.add.entry '(M_AH_L_P_K nil (((m ah l p k) 0))
(lex.add.entry '(T_UW_N_T_P_T_N nil (((t uw n t p t n) 0))
(lex.add.entry '(K_IY_N_T nil (((k iy n t) 0))
(lex.add.entry '(R_AY nil (((r ay) 0))
(lex.add.entry '(B_L_AY nil (((b l ay) 0))
(lex.add.entry '(HH_IY_T_K nil (((hh iy t k) 0))
(lex.add.entry '(B_L_AH nil (((b l ah) 0))
(lex.add.entry '(HH_IY_T_T nil (((hh iy t t) 0))
(lex.add.entry '(N_AH_R_D nil (((n ah r d) 0))
(lex.add.entry '(HH_IY_N_T nil (((hh iy n t) 0))
(lex.add.entry '(Z_AH_K_T nil (((z ah k t) 0))
(lex.add.entry '(N_AH_R_K nil (((n ah r k) 0))
(lex.add.entry '(N_AH_R_T nil (((n ah r t) 0))
(lex.add.entry '(N_AH_R_P nil (((n ah r p) 0))
(lex.add.entry '(N_AH_R_S nil (((n ah r s) 0))
(lex.add.entry '(HH_IY_N_L nil (((hh iy n l) 0))
(lex.add.entry '(N_AH_R_Z nil (((n ah r z) 0))
(lex.add.entry '(N_Y_AH_L_K nil (((n y ah l k) 0))
(lex.add.entry '(N_Y_AH_L_D nil (((n y ah l d) 0))
(lex.add.entry '(N_Y_AH_L_T nil (((n y ah l t) 0))
(lex.add.entry '(N_Y_AH_L_P nil (((n y ah l p) 0))
(lex.add.entry '(N_Y_AH_N_L nil (((n y ah n l) 0))
(lex.add.entry '(L_AH_P_K nil (((l ah p k) 0))
(lex.add.entry '(L_AH_P_T nil (((l ah p t) 0))
(lex.add.entry '(S_IY_CH_T nil (((s iy ch t) 0))
(lex.add.entry '(N_EH_CH_T nil (((n eh ch t) 0))
(lex.add.entry '(B_IY_L_N_T_K nil (((b iy l n t k) 0))
(lex.add.entry '(M nil (((m) 0))
(lex.add.entry '(D_IY nil (((d iy) 0))
(lex.add.entry '(T_IY_T_T_P nil (((t iy t t p) 0))
(lex.add.entry '(D_IH nil (((d ih) 0))
(lex.add.entry '(Y_EH_N_D nil (((y eh n d) 0))
(lex.add.entry '(G_L_AH nil (((g l ah) 0))
(lex.add.entry '(N_AH_K_D nil (((n ah k d) 0))
(lex.add.entry '(D_AH_L_N_K nil (((d ah l n k) 0))
(lex.add.entry '(G_L_AO nil (((g l ao) 0))
(lex.add.entry '(N_AH_K_L nil (((n ah k l) 0))
(lex.add.entry '(SH_EH nil (((sh eh) 0))
(lex.add.entry '(G_L_AY nil (((g l ay) 0))
(lex.add.entry '(AH_R_K_T nil (((ah r k t) 0))
(lex.add.entry '(S_L_AH_N_L nil (((s l ah n l) 0))
(lex.add.entry '(D_AH_L_N_T nil (((d ah l n t) 0))
(lex.add.entry '(N_IY_L_N nil (((n iy l n) 0))
(lex.add.entry '(N_IY_N_T nil (((n iy n t) 0))
(lex.add.entry '(CH_IY nil (((ch iy) 0))
(lex.add.entry '(P_OW_N nil (((p ow n) 0))
(lex.add.entry '(P_OW_L nil (((p ow l) 0))
(lex.add.entry '(P_OW_R nil (((p ow r) 0))
(lex.add.entry '(P_OW_S nil (((p ow s) 0))
(lex.add.entry '(N_IY_N_D nil (((n iy n d) 0))
(lex.add.entry '(N_IY_N_L nil (((n iy n l) 0))
(lex.add.entry '(N_AH_R_P_T nil (((n ah r p t) 0))
(lex.add.entry '(T_UW_D nil (((t uw d) 0))
(lex.add.entry '(Z_EH_R_K nil (((z eh r k) 0))
(lex.add.entry '(T_UW_M nil (((t uw m) 0))
(lex.add.entry '(T_UW_N nil (((t uw n) 0))
(lex.add.entry '(Z_EH nil (((z eh) 0))
(lex.add.entry '(B_R_IY nil (((b r iy) 0))
(lex.add.entry '(L_AH_T_N nil (((l ah t n) 0))
(lex.add.entry '(L_AH_T_K nil (((l ah t k) 0))
(lex.add.entry '(T_EH_T_S nil (((t eh t s) 0))
(lex.add.entry '(B_AH_R_K_M nil (((b ah r k m) 0))
(lex.add.entry '(T_EH_T_K nil (((t eh t k) 0))
(lex.add.entry '(T_EH_T_L nil (((t eh t l) 0))
(lex.add.entry '(L_AH_T_S nil (((l ah t s) 0))
(lex.add.entry '(L_AH_N_R nil (((l ah n r) 0))
(lex.add.entry '(L_AH_N_S nil (((l ah n s) 0))
(lex.add.entry '(S_M_AH nil (((s m ah) 0))
(lex.add.entry '(T_EH_R_N nil (((t eh r n) 0))
(lex.add.entry '(L_AH_N_T nil (((l ah n t) 0))
(lex.add.entry '(K_AY_T_T nil (((k ay t t) 0))
(lex.add.entry '(K_AY_T_L nil (((k ay t l) 0))
(lex.add.entry '(L_AH_N_D nil (((l ah n d) 0))
(lex.add.entry '(L_AH_N_K nil (((l ah n k) 0))
(lex.add.entry '(T_EH_R_T nil (((t eh r t) 0))
(lex.add.entry '(L_AH_N_M nil (((l ah n m) 0))
(lex.add.entry '(N_IY_CH_S nil (((n iy ch s) 0))
(lex.add.entry '(G_EH_G_N nil (((g eh g n) 0))
(lex.add.entry '(B_AH_S nil (((b ah s) 0))
(lex.add.entry '(N_IY_CH_T nil (((n iy ch t) 0))
(lex.add.entry '(SH_AH_R_K nil (((sh ah r k) 0))
(lex.add.entry '(T_EY nil (((t ey) 0))
(lex.add.entry '(S_K_OW_N_S nil (((s k ow n s) 0))
(lex.add.entry '(SH_AH_L_P nil (((sh ah l p) 0))
(lex.add.entry '(M_AY_N_S nil (((m ay n s) 0))
(lex.add.entry '(L_AH_S_T nil (((l ah s t) 0))
(lex.add.entry '(AH_N_T_K nil (((ah n t k) 0))
(lex.add.entry '(AH_N_T_L nil (((ah n t l) 0))
(lex.add.entry '(AH_P_G_L nil (((ah p g l) 0))
(lex.add.entry '(B_AH_N_T nil (((b ah n t) 0))
(lex.add.entry '(K_L_IY_CH nil (((k l iy ch) 0))
(lex.add.entry '(B_AH_N_P nil (((b ah n p) 0))
(lex.add.entry '(B_AH_L_K nil (((b ah l k) 0))
(lex.add.entry '(B_AH_L_N nil (((b ah l n) 0))
(lex.add.entry '(B_AH_L_M nil (((b ah l m) 0))
(lex.add.entry '(B_AH_L_S nil (((b ah l s) 0))
(lex.add.entry '(B_AH_L_P nil (((b ah l p) 0))
(lex.add.entry '(B_AH_L_T nil (((b ah l t) 0))
(lex.add.entry '(B_AH_N_L nil (((b ah n l) 0))
(lex.add.entry '(M_AH_S_M nil (((m ah s m) 0))
(lex.add.entry '(HH_IY_N_L_N nil (((hh iy n l n) 0))
(lex.add.entry '(B_AH_R_P nil (((b ah r p) 0))
(lex.add.entry '(AH_N_S nil (((ah n s) 0))
(lex.add.entry '(B_AH_R_S nil (((b ah r s) 0))
(lex.add.entry '(B_AH_R_T nil (((b ah r t) 0))
(lex.add.entry '(B_AH_R_K nil (((b ah r k) 0))
(lex.add.entry '(AH_N_L_N nil (((ah n l n) 0))
(lex.add.entry '(B_AH_R_D nil (((b ah r d) 0))
(lex.add.entry '(N nil (((n) 0))
(lex.add.entry '(N_IY_T nil (((n iy t) 0))
(lex.add.entry '(S_F_EH nil (((s f eh) 0))
(lex.add.entry '(N_AY_N_T nil (((n ay n t) 0))
(lex.add.entry '(L_AH_NG_K_T nil (((l ah ng k t) 0))
(lex.add.entry '(N_AY_N_K nil (((n ay n k) 0))
(lex.add.entry '(B_AH_R_K_T nil (((b ah r k t) 0))
(lex.add.entry '(M_EY_N_T nil (((m ey n t) 0))
(lex.add.entry '(R_OW nil (((r ow) 0))
(lex.add.entry '(IY_CH nil (((iy ch) 0))
(lex.add.entry '(N_OW_P nil (((n ow p) 0))
(lex.add.entry '(N_OW_R nil (((n ow r) 0))
(lex.add.entry '(N_OW_T nil (((n ow t) 0))
(lex.add.entry '(N_OW_K nil (((n ow k) 0))
(lex.add.entry '(N_OW_L nil (((n ow l) 0))
(lex.add.entry '(N_OW_M nil (((n ow m) 0))
(lex.add.entry '(N_OW_N nil (((n ow n) 0))
(lex.add.entry '(L_IY_NG nil (((l iy ng) 0))
(lex.add.entry '(HH_IY_N_T_P nil (((hh iy n t p) 0))
(lex.add.entry '(T_IY_S_T nil (((t iy s t) 0))
(lex.add.entry '(R_AH_N_L_N nil (((r ah n l n) 0))
(lex.add.entry '(S_K_AH_R nil (((s k ah r) 0))
(lex.add.entry '(T_K nil (((t k) 0))
(lex.add.entry '(K_AY_L_T nil (((k ay l t) 0))
(lex.add.entry '(L_Y_EH_L_D nil (((l y eh l d) 0))
(lex.add.entry '(K_AY_L_P nil (((k ay l p) 0))
(lex.add.entry '(K_L_IY_N_T nil (((k l iy n t) 0))
(lex.add.entry '(K_AY_L_D nil (((k ay l d) 0))
(lex.add.entry '(K_AY_N_T nil (((k ay n t) 0))
(lex.add.entry '(M_UW_NG nil (((m uw ng) 0))
(lex.add.entry '(K_AY_L_N nil (((k ay l n) 0))
(lex.add.entry '(N_AH_NG nil (((n ah ng) 0))
(lex.add.entry '(M_AH_L_D nil (((m ah l d) 0))
(lex.add.entry '(N_IY_T_K nil (((n iy t k) 0))
(lex.add.entry '(N_IY_T_T nil (((n iy t t) 0))
(lex.add.entry '(N_IY_T_S nil (((n iy t s) 0))
(lex.add.entry '(V_AO nil (((v ao) 0))
(lex.add.entry '(T_AY_N_T_T nil (((t ay n t t) 0))
(lex.add.entry '(IY_N_L_N nil (((iy n l n) 0))
(lex.add.entry '(S_F_EH_R nil (((s f eh r) 0))
(lex.add.entry '(S_F_EH_K nil (((s f eh k) 0))
(lex.add.entry '(G_AH_L_P_K nil (((g ah l p k) 0))
(lex.add.entry '(T_AY_N_T_K nil (((t ay n t k) 0))
(lex.add.entry '(K_L_IY_L_P nil (((k l iy l p) 0))
(lex.add.entry '(M_AY nil (((m ay) 0))
(lex.add.entry '(S_IY_L nil (((s iy l) 0))
(lex.add.entry '(T_EH_N_D nil (((t eh n d) 0))
(lex.add.entry '(G_AH_NG_M nil (((g ah ng m) 0))
(lex.add.entry '(L_AH_N_L nil (((l ah n l) 0))
(lex.add.entry '(M_AO nil (((m ao) 0))
(lex.add.entry '(F_AO_R_Z nil (((f ao r z) 0))
(lex.add.entry '(G_AH_NG_S nil (((g ah ng s) 0))
(lex.add.entry '(G_AH_NG_T nil (((g ah ng t) 0))
(lex.add.entry '(OY nil (((oy) 0))
(lex.add.entry '(M_AH nil (((m ah) 0))
(lex.add.entry '(OW nil (((ow) 0))
(lex.add.entry '(T_EH_N_T nil (((t eh n t) 0))
(lex.add.entry '(K_L_IY_L_N nil (((k l iy l n) 0))
(lex.add.entry '(T_EH_L_N nil (((t eh l n) 0))
(lex.add.entry '(M_AH_L_N_T nil (((m ah l n t) 0))
(lex.add.entry '(HH_AO_S nil (((hh ao s) 0))
(lex.add.entry '(HH_AO_L nil (((hh ao l) 0))
(lex.add.entry '(M_AH_L_N_L nil (((m ah l n l) 0))
(lex.add.entry '(HH_AO_K nil (((hh ao k) 0))
(lex.add.entry '(T_AH_R_K_K nil (((t ah r k k) 0))
(lex.add.entry '(T_AH_R_N nil (((t ah r n) 0))
(lex.add.entry '(T_AH_R_L nil (((t ah r l) 0))
(lex.add.entry '(T_AH_R_K nil (((t ah r k) 0))
(lex.add.entry '(T_IY_NG_K nil (((t iy ng k) 0))
(lex.add.entry '(K_AH_N_L_N nil (((k ah n l n) 0))
(lex.add.entry '(K_EH nil (((k eh) 0))
(lex.add.entry '(CH_AH_N_L nil (((ch ah n l) 0))
(lex.add.entry '(CH_AH_N_M nil (((ch ah n m) 0))
(lex.add.entry '(T_AH_R_T nil (((t ah r t) 0))
(lex.add.entry '(T_Y_AO_N nil (((t y ao n) 0))
(lex.add.entry '(T_AH_R_P nil (((t ah r p) 0))
(lex.add.entry '(K_OW_S nil (((k ow s) 0))
(lex.add.entry '(M_OY_R nil (((m oy r) 0))
(lex.add.entry '(G_AH_K_T nil (((g ah k t) 0))
(lex.add.entry '(Y_EH_N_T nil (((y eh n t) 0))
(lex.add.entry '(D_AH_NG nil (((d ah ng) 0))
(lex.add.entry '(K_OW_N nil (((k ow n) 0))
(lex.add.entry '(K_OW_M nil (((k ow m) 0))
(lex.add.entry '(K_OW_L nil (((k ow l) 0))
(lex.add.entry '(AH_R_T nil (((ah r t) 0))
(lex.add.entry '(N_IY_CH nil (((n iy ch) 0))
(lex.add.entry '(AH_R_K nil (((ah r k) 0))
(lex.add.entry '(S_K_OW_N nil (((s k ow n) 0))
(lex.add.entry '(S_K_OW_L nil (((s k ow l) 0))
(lex.add.entry '(S_K_OW_K nil (((s k ow k) 0))
(lex.add.entry '(D_Y_AO_N nil (((d y ao n) 0))
(lex.add.entry '(R_AH_NG nil (((r ah ng) 0))
(lex.add.entry '(M_AH_K_T nil (((m ah k t) 0))
(lex.add.entry '(S_T_AY_N_D nil (((s t ay n d) 0))
(lex.add.entry '(M_AH_K_L nil (((m ah k l) 0))
(lex.add.entry '(S_IY_N_D nil (((s iy n d) 0))
(lex.add.entry '(L_AH_N_T_L_N nil (((l ah n t l n) 0))
(lex.add.entry '(S_IY_N_P nil (((s iy n p) 0))
(lex.add.entry '(S_IY_N_T nil (((s iy n t) 0))
(lex.add.entry '(L_EH_S_T nil (((l eh s t) 0))
(lex.add.entry '(L_AH_N_T_P_T nil (((l ah n t p t) 0))
(lex.add.entry '(R_OW_K nil (((r ow k) 0))
(lex.add.entry '(SH_UW nil (((sh uw) 0))
(lex.add.entry '(M_EY_P_L nil (((m ey p l) 0))
(lex.add.entry '(B_IY_D nil (((b iy d) 0))
(lex.add.entry '(Z_IY_CH_T nil (((z iy ch t) 0))
(lex.add.entry '(B_IY_L nil (((b iy l) 0))
(lex.add.entry '(B_IY_N nil (((b iy n) 0))
(lex.add.entry '(S_M_IY_S_K nil (((s m iy s k) 0))
(lex.add.entry '(B_IY_S nil (((b iy s) 0))
(lex.add.entry '(B_IY_T nil (((b iy t) 0))
(lex.add.entry '(S_T_AO_K nil (((s t ao k) 0))
(lex.add.entry '(S_T_AO_N nil (((s t ao n) 0))
(lex.add.entry '(T_AH_N_K nil (((t ah n k) 0))
(lex.add.entry '(D_IY_L_N nil (((d iy l n) 0))
(lex.add.entry '(T_AH_N_N nil (((t ah n n) 0))
(lex.add.entry '(T_AH_L_Z nil (((t ah l z) 0))
(lex.add.entry '(N_EH_N_T_K_T nil (((n eh n t k t) 0))
(lex.add.entry '(S_IY_T_T nil (((s iy t t) 0))
(lex.add.entry '(M_EY_T_K nil (((m ey t k) 0))
(lex.add.entry '(D_IY_L_N_T nil (((d iy l n t) 0))
(lex.add.entry '(SH_L_AH_N nil (((sh l ah n) 0))
(lex.add.entry '(T_AH_L_S nil (((t ah l s) 0))
(lex.add.entry '(M_EY_T_S nil (((m ey t s) 0))
(lex.add.entry '(T_AH_L_N nil (((t ah l n) 0))
(lex.add.entry '(T_AH_L_K nil (((t ah l k) 0))
(lex.add.entry '(T_AH_L_D nil (((t ah l d) 0))
(lex.add.entry '(Z_EH_R_K_N_T nil (((z eh r k n t) 0))
(lex.add.entry '(T_AH_N_T nil (((t ah n t) 0))
(lex.add.entry '(T_AY_L_P_K nil (((t ay l p k) 0))
(lex.add.entry '(D_EH_R_K_T nil (((d eh r k t) 0))
(lex.add.entry '(V_AH_M nil (((v ah m) 0))
(lex.add.entry '(V_AH_L nil (((v ah l) 0))
(lex.add.entry '(B_AY_T nil (((b ay t) 0))
(lex.add.entry '(AO nil (((ao) 0))
(lex.add.entry '(B_AY_L nil (((b ay l) 0))
(lex.add.entry '(B_AY_M nil (((b ay m) 0))
(lex.add.entry '(B_AY_N nil (((b ay n) 0))
(lex.add.entry '(B_IH_N_T_P nil (((b ih n t p) 0))
(lex.add.entry '(AY nil (((ay) 0))
(lex.add.entry '(B_AY_D nil (((b ay d) 0))
(lex.add.entry '(N_AH_K_T nil (((n ah k t) 0))
(lex.add.entry '(G_UW_NG nil (((g uw ng) 0))
(lex.add.entry '(D_IY_K nil (((d iy k) 0))
(lex.add.entry '(D_IY_N nil (((d iy n) 0))
(lex.add.entry '(D_IY_L nil (((d iy l) 0))
(lex.add.entry '(D_IY_M nil (((d iy m) 0))
(lex.add.entry '(M_AH_N_L_N nil (((m ah n l n) 0))
(lex.add.entry '(D_IY_G nil (((d iy g) 0))
(lex.add.entry '(D_IY_D nil (((d iy d) 0))
(lex.add.entry '(D_IY_Z nil (((d iy z) 0))
(lex.add.entry '(F_AH_NG nil (((f ah ng) 0))
(lex.add.entry '(D_IY_R nil (((d iy r) 0))
(lex.add.entry '(D_IY_S nil (((d iy s) 0))
(lex.add.entry '(M_EY_N_T_K nil (((m ey n t k) 0))
(lex.add.entry '(D_IY_T nil (((d iy t) 0))
(lex.add.entry '(L_AH_NG nil (((l ah ng) 0))
(lex.add.entry '(Y_EH_N_T_K nil (((y eh n t k) 0))
(lex.add.entry '(P nil (((p) 0))
(lex.add.entry '(HH_IY_CH nil (((hh iy ch) 0))
(lex.add.entry '(F_IY_S nil (((f iy s) 0))
(lex.add.entry '(S_AH_L_N_S nil (((s ah l n s) 0))
(lex.add.entry '(S_AH_L_N_T nil (((s ah l n t) 0))
(lex.add.entry '(Z_AH_K nil (((z ah k) 0))
(lex.add.entry '(Z_AH_M nil (((z ah m) 0))
(lex.add.entry '(Z_AH_L nil (((z ah l) 0))
(lex.add.entry '(Z_AH_N nil (((z ah n) 0))
(lex.add.entry '(L_Y_AH nil (((l y ah) 0))
(lex.add.entry '(B_AY_CH nil (((b ay ch) 0))
(lex.add.entry '(Z_AH_P nil (((z ah p) 0))
(lex.add.entry '(Z_AH_S nil (((z ah s) 0))
(lex.add.entry '(Z_AH_R nil (((z ah r) 0))
(lex.add.entry '(Z_AH_T nil (((z ah t) 0))
(lex.add.entry '(M_AH_L_P_S nil (((m ah l p s) 0))
(lex.add.entry '(T_UW nil (((t uw) 0))
(lex.add.entry '(M_AH_L_T_K nil (((m ah l t k) 0))
(lex.add.entry '(SH_AH_T nil (((sh ah t) 0))
(lex.add.entry '(S_AH_L_P_T nil (((s ah l p t) 0))
(lex.add.entry '(AY_CH nil (((ay ch) 0))
(lex.add.entry '(HH_AY_CH nil (((hh ay ch) 0))
(lex.add.entry '(S_T_IH_T nil (((s t ih t) 0))
(lex.add.entry '(Z_AY_T nil (((z ay t) 0))
(lex.add.entry '(EY_NG nil (((ey ng) 0))
(lex.add.entry '(S_OW_L nil (((s ow l) 0))
(lex.add.entry '(S_AY_CH nil (((s ay ch) 0))
(lex.add.entry '(Z_AY_N nil (((z ay n) 0))
(lex.add.entry '(T_Y_EH_L_P nil (((t y eh l p) 0))
(lex.add.entry '(T_Y_EH_L_N nil (((t y eh l n) 0))
(lex.add.entry '(D_Y_AH nil (((d y ah) 0))
(lex.add.entry '(T_Y_EH_N_S nil (((t y eh n s) 0))
(lex.add.entry '(T_Y_EH_N_T nil (((t y eh n t) 0))
(lex.add.entry '(K_L_EH_N nil (((k l eh n) 0))
(lex.add.entry '(K_L_EH_K nil (((k l eh k) 0))
(lex.add.entry '(V_AH nil (((v ah) 0))
(lex.add.entry '(G_OW_N nil (((g ow n) 0))
(lex.add.entry '(V_AY nil (((v ay) 0))
(lex.add.entry '(D_AH_L_N_K_T nil (((d ah l n k t) 0))
(lex.add.entry '(UW_NG nil (((uw ng) 0))
(lex.add.entry '(L_AO_D nil (((l ao d) 0))
(lex.add.entry '(L_AO_K nil (((l ao k) 0))
(lex.add.entry '(L_AO_N nil (((l ao n) 0))
(lex.add.entry '(L_AO_P nil (((l ao p) 0))
(lex.add.entry '(S_T_IY_N nil (((s t iy n) 0))
(lex.add.entry '(S_EH_K_T nil (((s eh k t) 0))
(lex.add.entry '(AH_L_P nil (((ah l p) 0))
(lex.add.entry '(V_EH_N nil (((v eh n) 0))
(lex.add.entry '(AH_L_D nil (((ah l d) 0))
(lex.add.entry '(V_EH_R nil (((v eh r) 0))
(lex.add.entry '(UW nil (((uw) 0))
(lex.add.entry '(CH_EH nil (((ch eh) 0))
(lex.add.entry '(AH_L_N nil (((ah l n) 0))
(lex.add.entry '(L_AY_N nil (((l ay n) 0))
(lex.add.entry '(L_AY_L nil (((l ay l) 0))
(lex.add.entry '(N_AH_N_P_L nil (((n ah n p l) 0))
(lex.add.entry '(HH_OW nil (((hh ow) 0))
(lex.add.entry '(T_AH_L_P_K nil (((t ah l p k) 0))
(lex.add.entry '(L_AY_S nil (((l ay s) 0))
(lex.add.entry '(L_AY_P nil (((l ay p) 0))
(lex.add.entry '(N_OW_R_D nil (((n ow r d) 0))
(lex.add.entry '(L_AY_T nil (((l ay t) 0))
(lex.add.entry '(T_AH_L_P_M nil (((t ah l p m) 0))
(lex.add.entry '(L_AY_P_T_K nil (((l ay p t k) 0))
(lex.add.entry '(N_OW_L_T nil (((n ow l t) 0))
(lex.add.entry '(D_IY_NG_T nil (((d iy ng t) 0))
(lex.add.entry '(N_UW nil (((n uw) 0))
(lex.add.entry '(M_Y_AH_R_D nil (((m y ah r d) 0))
(lex.add.entry '(P_AH nil (((p ah) 0))
(lex.add.entry '(S_EH nil (((s eh) 0))
(lex.add.entry '(T_IH nil (((t ih) 0))
(lex.add.entry '(Y_AH_N nil (((y ah n) 0))
(lex.add.entry '(N_AH_N_T_L nil (((n ah n t l) 0))
(lex.add.entry '(V_EH_N_N nil (((v eh n n) 0))
(lex.add.entry '(P_AY nil (((p ay) 0))
(lex.add.entry '(V_EH_L_P nil (((v eh l p) 0))
(lex.add.entry '(T_IY nil (((t iy) 0))
(lex.add.entry '(OW_R nil (((ow r) 0))
(lex.add.entry '(T_IY_V_R nil (((t iy v r) 0))
(lex.add.entry '(B_IY_T_D nil (((b iy t d) 0))
(lex.add.entry '(B_IY_T_K nil (((b iy t k) 0))
(lex.add.entry '(N_AH_N_L_N nil (((n ah n l n) 0))
(lex.add.entry '(M_IY_T_T nil (((m iy t t) 0))
(lex.add.entry '(HH_AH_L_Z nil (((hh ah l z) 0))
(lex.add.entry '(M_IY_T_S nil (((m iy t s) 0))
(lex.add.entry '(T_EH_R_K nil (((t eh r k) 0))
(lex.add.entry '(SH_EH_N nil (((sh eh n) 0))
(lex.add.entry '(F_AH_N_L nil (((f ah n l) 0))
(lex.add.entry '(N_Y_AO_R nil (((n y ao r) 0))
(lex.add.entry '(Z_EH_L nil (((z eh l) 0))
(lex.add.entry '(Z_EH_N nil (((z eh n) 0))
(lex.add.entry '(S_IY_CH nil (((s iy ch) 0))
(lex.add.entry '(Z_EH_K nil (((z eh k) 0))
(lex.add.entry '(Z_EH_T nil (((z eh t) 0))
(lex.add.entry '(Z_EH_P nil (((z eh p) 0))
(lex.add.entry '(Z_EH_R nil (((z eh r) 0))
(lex.add.entry '(EH_N nil (((eh n) 0))
(lex.add.entry '(N_Y_AO_N nil (((n y ao n) 0))
(lex.add.entry '(L_AO_P_T nil (((l ao p t) 0))
(lex.add.entry '(M_EY nil (((m ey) 0))
(lex.add.entry '(P_L_AY_P nil (((p l ay p) 0))
(lex.add.entry '(OW_L nil (((ow l) 0))
(lex.add.entry '(HH_AH_N_S nil (((hh ah n s) 0))
(lex.add.entry '(P_IH_T nil (((p ih t) 0))
(lex.add.entry '(T_Y_OW nil (((t y ow) 0))
(lex.add.entry '(P_AH_L_T nil (((p ah l t) 0))
(lex.add.entry '(P_AH_N_G nil (((p ah n g) 0))
(lex.add.entry '(S_EH_P_L_T nil (((s eh p l t) 0))
(lex.add.entry '(P_AH_N_T nil (((p ah n t) 0))
(lex.add.entry '(P_AH_L_N nil (((p ah l n) 0))
(lex.add.entry '(T_AY_L_N_T_L nil (((t ay l n t l) 0))
(lex.add.entry '(K_L_AH_N nil (((k l ah n) 0))
(lex.add.entry '(K_L_AH_M nil (((k l ah m) 0))
(lex.add.entry '(N_Y_EH nil (((n y eh) 0))
(lex.add.entry '(K_L_AH_G nil (((k l ah g) 0))
(lex.add.entry '(S_M_IY_T nil (((s m iy t) 0))
(lex.add.entry '(K_L_AH_S nil (((k l ah s) 0))
(lex.add.entry '(K_L_AH_T nil (((k l ah t) 0))
(lex.add.entry '(K_AH_L_P_HH_NG nil (((k ah l p hh ng) 0))
(lex.add.entry '(G_OW nil (((g ow) 0))
(lex.add.entry '(T_EH nil (((t eh) 0))
(lex.add.entry '(AO_N nil (((ao n) 0))
(lex.add.entry '(L_AY_P_T nil (((l ay p t) 0))
(lex.add.entry '(AO_K nil (((ao k) 0))
(lex.add.entry '(G_AY nil (((g ay) 0))
(lex.add.entry '(HH_OW_L nil (((hh ow l) 0))
(lex.add.entry '(G_AH nil (((g ah) 0))
(lex.add.entry '(D_Y_OW_N nil (((d y ow n) 0))
(lex.add.entry '(N_Y_AH_NG nil (((n y ah ng) 0))
(lex.add.entry '(AH_NG nil (((ah ng) 0))
(lex.add.entry '(AH_NG_M nil (((ah ng m) 0))
(lex.add.entry '(L_IH nil (((l ih) 0))
(lex.add.entry '(K_R_AH nil (((k r ah) 0))
(lex.add.entry '(S_K_OW_L_K nil (((s k ow l k) 0))
(lex.add.entry '(L_IY nil (((l iy) 0))
(lex.add.entry '(M_AY_CH nil (((m ay ch) 0))
(lex.add.entry '(CH_EH_N nil (((ch eh n) 0))
(lex.add.entry '(K_IY nil (((k iy) 0))
(lex.add.entry '(K_OW_N_L_N_L_T nil (((k ow n l n l t) 0))
(lex.add.entry '(Y_AH_L nil (((y ah l) 0))
(lex.add.entry '(K_AY_N_T_K nil (((k ay n t k) 0))
(lex.add.entry '(K_IH nil (((k ih) 0))
(lex.add.entry '(CH_EH_T nil (((ch eh t) 0))
(lex.add.entry '(P_AO nil (((p ao) 0))
(lex.add.entry '(CH_EH_S nil (((ch eh s) 0))
(lex.add.entry '(CH_EH_R nil (((ch eh r) 0))
(lex.add.entry '(P_AH_R_K nil (((p ah r k) 0))
(lex.add.entry '(P_OW_S_T nil (((p ow s t) 0))
(lex.add.entry '(R_AH_NG_K nil (((r ah ng k) 0))
(lex.add.entry '(P_AH_R_P nil (((p ah r p) 0))
(lex.add.entry '(D_AH_S nil (((d ah s) 0))
(lex.add.entry '(D_AH_R nil (((d ah r) 0))
(lex.add.entry '(D_AH_P nil (((d ah p) 0))
(lex.add.entry '(D_AH_T nil (((d ah t) 0))
(lex.add.entry '(D_AH_K nil (((d ah k) 0))
(lex.add.entry '(D_AH_N nil (((d ah n) 0))
(lex.add.entry '(D_AH_M nil (((d ah m) 0))
(lex.add.entry '(D_AH_L nil (((d ah l) 0))
(lex.add.entry '(S_EH_R_D nil (((s eh r d) 0))
(lex.add.entry '(P_EH_K nil (((p eh k) 0))
(lex.add.entry '(S_N_IY_CH nil (((s n iy ch) 0))
(lex.add.entry '(L_AY_L_P nil (((l ay l p) 0))
(lex.add.entry '(L_AY_N_D nil (((l ay n d) 0))
(lex.add.entry '(K_AH_L_N nil (((k ah l n) 0))
(lex.add.entry '(L_AY_L_D nil (((l ay l d) 0))
(lex.add.entry '(K_AH_L_P nil (((k ah l p) 0))
(lex.add.entry '(K_AH_L_S nil (((k ah l s) 0))
(lex.add.entry '(L_Y_AH_L_N_T nil (((l y ah l n t) 0))
(lex.add.entry '(P_EH_R nil (((p eh r) 0))
(lex.add.entry '(K_AH_R_K nil (((k ah r k) 0))
(lex.add.entry '(HH_AH_L_M_L nil (((hh ah l m l) 0))
(lex.add.entry '(M_AH_NG_K nil (((m ah ng k) 0))
(lex.add.entry '(K_AH_P_L nil (((k ah p l) 0))
(lex.add.entry '(UW_M nil (((uw m) 0))
(lex.add.entry '(UW_N nil (((uw n) 0))
(lex.add.entry '(N_AH_NG_K nil (((n ah ng k) 0))
(lex.add.entry '(V_L_IY_CH nil (((v l iy ch) 0))
(lex.add.entry '(M_OW_N_T nil (((m ow n t) 0))
(lex.add.entry '(T_AH_L_N_T nil (((t ah l n t) 0))
(lex.add.entry '(CH_AY_N nil (((ch ay n) 0))
(lex.add.entry '(Z_IY_L nil (((z iy l) 0))
(lex.add.entry '(Z_IY_M nil (((z iy m) 0))
(lex.add.entry '(Z_IY_N nil (((z iy n) 0))
(lex.add.entry '(K_AH_N_T nil (((k ah n t) 0))
(lex.add.entry '(L_IY_S_T nil (((l iy s t) 0))
(lex.add.entry '(Z_IY_S nil (((z iy s) 0))
(lex.add.entry '(Z_IY_T nil (((z iy t) 0))
(lex.add.entry '(K_AH_N_L nil (((k ah n l) 0))
(lex.add.entry '(N_EH_R_K nil (((n eh r k) 0))
(lex.add.entry '(G_AH_NG nil (((g ah ng) 0))
(lex.add.entry '(N_EH_R_S nil (((n eh r s) 0))
(lex.add.entry '(N_EH_R_T nil (((n eh r t) 0))
(lex.add.entry '(D_EH_R_S nil (((d eh r s) 0))
(lex.add.entry '(D_EH_R_P nil (((d eh r p) 0))
(lex.add.entry '(D_EH_R_T nil (((d eh r t) 0))
(lex.add.entry '(D_EH_R_K nil (((d eh r k) 0))
(lex.add.entry '(D_EH_R_N nil (((d eh r n) 0))
(lex.add.entry '(D_EH_T_S nil (((d eh t s) 0))
(lex.add.entry '(D_EH_R_D nil (((d eh r d) 0))
(lex.add.entry '(D_EH_N_T_K nil (((d eh n t k) 0))
(lex.add.entry '(D_EH_N_T_L nil (((d eh n t l) 0))
(lex.add.entry '(K_AH_N_NG nil (((k ah n ng) 0))
(lex.add.entry '(S nil (((s) 0))
(lex.add.entry '(S_T_AH_F_R nil (((s t ah f r) 0))
(lex.add.entry '(SH_AH nil (((sh ah) 0))
(lex.add.entry '(SH_AY nil (((sh ay) 0))
(lex.add.entry '(EH_S_T nil (((eh s t) 0))
(lex.add.entry '(B_AY_L_N_L nil (((b ay l n l) 0))
(lex.add.entry '(F_EH_K_S nil (((f eh k s) 0))
(lex.add.entry '(Z_IH nil (((z ih) 0))
(lex.add.entry '(L_IY_G nil (((l iy g) 0))
(lex.add.entry '(L_IY_K nil (((l iy k) 0))
(lex.add.entry '(L_IY_N nil (((l iy n) 0))
(lex.add.entry '(L_IY_L nil (((l iy l) 0))
(lex.add.entry '(L_IY_M nil (((l iy m) 0))
(lex.add.entry '(L_IY_S nil (((l iy s) 0))
(lex.add.entry '(Z_IY nil (((z iy) 0))
(lex.add.entry '(L_IY_T nil (((l iy t) 0))
(lex.add.entry '(G_Y_AO_N nil (((g y ao n) 0))
(lex.add.entry '(D_EH_P_N nil (((d eh p n) 0))
(lex.add.entry '(HH_AH_L_N_T nil (((hh ah l n t) 0))
(lex.add.entry '(D_EH_N_T nil (((d eh n t) 0))
(lex.add.entry '(HH_AH_L_N_L nil (((hh ah l n l) 0))
(lex.add.entry '(N_EH_L_D nil (((n eh l d) 0))
(lex.add.entry '(D_EH_P_T nil (((d eh p t) 0))
(lex.add.entry '(D_EH_N_D nil (((d eh n d) 0))
(lex.add.entry '(N_EH_L_N nil (((n eh l n) 0))
(lex.add.entry '(N_EH_L_M nil (((n eh l m) 0))
(lex.add.entry '(L_IY_T_D nil (((l iy t d) 0))
(lex.add.entry '(D_EH_L_D nil (((d eh l d) 0))
(lex.add.entry '(G_IY_CH nil (((g iy ch) 0))
(lex.add.entry '(T_IY_K_T_S nil (((t iy k t s) 0))
(lex.add.entry '(R_EH_N_D nil (((r eh n d) 0))
(lex.add.entry '(L_IY_T_K nil (((l iy t k) 0))
(lex.add.entry '(D_EH_L_P nil (((d eh l p) 0))
(lex.add.entry '(L_IY_T_T nil (((l iy t t) 0))
(lex.add.entry '(D_EH_L_Z nil (((d eh l z) 0))
(lex.add.entry '(R_EH_N_T nil (((r eh n t) 0))
(lex.add.entry '(Z_AH_L_N_T nil (((z ah l n t) 0))
(lex.add.entry '(B_Y_AH nil (((b y ah) 0))
(lex.add.entry '(K_AO_N nil (((k ao n) 0))
(lex.add.entry '(N_IY_T_L_N nil (((n iy t l n) 0))
(lex.add.entry '(L_IY_N_T_K nil (((l iy n t k) 0))
(lex.add.entry '(K_UW_NG nil (((k uw ng) 0))
(lex.add.entry '(S_N_IY nil (((s n iy) 0))
(lex.add.entry '(AH_N_P_L nil (((ah n p l) 0))
(lex.add.entry '(N_EH_CH nil (((n eh ch) 0))
(lex.add.entry '(B_AH_NG_S nil (((b ah ng s) 0))
(lex.add.entry '(B_AH_NG_T nil (((b ah ng t) 0))
(lex.add.entry '(P_L_IY_S_T nil (((p l iy s t) 0))
(lex.add.entry '(B_AH_NG_K nil (((b ah ng k) 0))
(lex.add.entry '(B_AH_NG_M nil (((b ah ng m) 0))
(lex.add.entry '(K_Y_EH_N nil (((k y eh n) 0))
(lex.add.entry '(L_AH_NG_M nil (((l ah ng m) 0))
(lex.add.entry '(L_AH_NG_K nil (((l ah ng k) 0))
(lex.add.entry '(N_AY_N nil (((n ay n) 0))
(lex.add.entry '(HH_IY nil (((hh iy) 0))
(lex.add.entry '(L_AH_NG_S nil (((l ah ng s) 0))
(lex.add.entry '(N_IY_L nil (((n iy l) 0))
(lex.add.entry '(N_IY_M nil (((n iy m) 0))
(lex.add.entry '(N_IY_N nil (((n iy n) 0))
(lex.add.entry '(N_IY_G nil (((n iy g) 0))
(lex.add.entry '(D_IY_N_T nil (((d iy n t) 0))
(lex.add.entry '(N_AH_N nil (((n ah n) 0))
(lex.add.entry '(K nil (((k) 0))
(lex.add.entry '(B_R_AH_L_P nil (((b r ah l p) 0))
(lex.add.entry '(L_AH_N_K_T nil (((l ah n k t) 0))
(lex.add.entry '(N_IY_S nil (((n iy s) 0))
(lex.add.entry '(HH_EH_R_N nil (((hh eh r n) 0))
(lex.add.entry '(HH_EH_R_K nil (((hh eh r k) 0))
(lex.add.entry '(HH_AH_NG nil (((hh ah ng) 0))
(lex.add.entry '(T nil (((t) 0))
(lex.add.entry '(HH_EH_R_T nil (((hh eh r t) 0))
(lex.add.entry '(HH_EH_R_S nil (((hh eh r s) 0))
(lex.add.entry '(HH_EH_R_P nil (((hh eh r p) 0))
(lex.add.entry '(Y_EH nil (((y eh) 0))
(lex.add.entry '(B_AY nil (((b ay) 0))
(lex.add.entry '(N_Y_UW nil (((n y uw) 0))
(lex.add.entry '(S_N_AH_R nil (((s n ah r) 0))
(lex.add.entry '(S_N_AH_L nil (((s n ah l) 0))
(lex.add.entry '(B_AH nil (((b ah) 0))
(lex.add.entry '(S_N_AH_N nil (((s n ah n) 0))
(lex.add.entry '(B_AO nil (((b ao) 0))
(lex.add.entry '(S_N_AH_K nil (((s n ah k) 0))
(lex.add.entry '(M_AO_S nil (((m ao s) 0))
(lex.add.entry '(S_T_IH nil (((s t ih) 0))
(lex.add.entry '(D_UW_NG nil (((d uw ng) 0))
(lex.add.entry '(S_T_IY nil (((s t iy) 0))
(lex.add.entry '(P_AH_S nil (((p ah s) 0))
(lex.add.entry '(P_AH_R nil (((p ah r) 0))
(lex.add.entry '(SH_EH_NG_K nil (((sh eh ng k) 0))
(lex.add.entry '(M_AH_L_N_T_L_Z nil (((m ah l n t l z) 0))
(lex.add.entry '(P_AH_N nil (((p ah n) 0))
(lex.add.entry '(B_AH_L_N_D_N nil (((b ah l n d n) 0))
(lex.add.entry '(P_AH_L nil (((p ah l) 0))
(lex.add.entry '(N_EH_K nil (((n eh k) 0))
(lex.add.entry '(N_EH_M nil (((n eh m) 0))
(lex.add.entry '(N_EH_L nil (((n eh l) 0))
(lex.add.entry '(N_EH_N nil (((n eh n) 0))
(lex.add.entry '(N_EH_R nil (((n eh r) 0))
(lex.add.entry '(N_EH_T nil (((n eh t) 0))
(lex.add.entry '(D_EH_N_L_N nil (((d eh n l n) 0))
(lex.add.entry '(R_AH_L_K nil (((r ah l k) 0))
(lex.add.entry '(R_AH_L_N nil (((r ah l n) 0))
(lex.add.entry '(R_AH_L_M nil (((r ah l m) 0))
(lex.add.entry '(D_IY_NG_L_N nil (((d iy ng l n) 0))
(lex.add.entry '(K_OW_L_N_T nil (((k ow l n t) 0))
(lex.add.entry '(M_EH nil (((m eh) 0))
(lex.add.entry '(N_IH nil (((n ih) 0))
(lex.add.entry '(L_AH_N_HH_R nil (((l ah n hh r) 0))
(lex.add.entry '(D_IY_S_T nil (((d iy s t) 0))
(lex.add.entry '(N_IY nil (((n iy) 0))
(lex.add.entry '(S_T_AY_L_M nil (((s t ay l m) 0))
(lex.add.entry '(S_T_AY_L_N nil (((s t ay l n) 0))
(lex.add.entry '(S_T_AY_L_K nil (((s t ay l k) 0))
(lex.add.entry '(HH_EH_L_N nil (((hh eh l n) 0))
(lex.add.entry '(N_AH_L_K_N nil (((n ah l k n) 0))
(lex.add.entry '(K_AY_T nil (((k ay t) 0))
(lex.add.entry '(T_EY_Z nil (((t ey z) 0))
(lex.add.entry '(L_IY_T_T_S nil (((l iy t t s) 0))
(lex.add.entry '(T_EY_T nil (((t ey t) 0))
(lex.add.entry '(T_EY_N nil (((t ey n) 0))
(lex.add.entry '(T_EY_L nil (((t ey l) 0))
(lex.add.entry '(P_T nil (((p t) 0))
(lex.add.entry '(T_AH_NG_S nil (((t ah ng s) 0))
(lex.add.entry '(T_AH_NG_P nil (((t ah ng p) 0))
(lex.add.entry '(T_Y_EH_NG nil (((t y eh ng) 0))
(lex.add.entry '(N_AH_T nil (((n ah t) 0))
(lex.add.entry '(N_AH_P nil (((n ah p) 0))
(lex.add.entry '(N_AH_S nil (((n ah s) 0))
(lex.add.entry '(N_AH_R nil (((n ah r) 0))
(lex.add.entry '(N_AH_M nil (((n ah m) 0))
(lex.add.entry '(N_AH_L nil (((n ah l) 0))
(lex.add.entry '(M_AH_N_T_L_N nil (((m ah n t l n) 0))
(lex.add.entry '(N_AH_K nil (((n ah k) 0))
(lex.add.entry '(T_UW_NG nil (((t uw ng) 0))
(lex.add.entry '(T_EH_S nil (((t eh s) 0))
(lex.add.entry '(T_EH_R nil (((t eh r) 0))
(lex.add.entry '(V_IY_CH_T nil (((v iy ch t) 0))
(lex.add.entry '(K_IY_N nil (((k iy n) 0))
(lex.add.entry '(T_EH_N nil (((t eh n) 0))
(lex.add.entry '(T_EH_M nil (((t eh m) 0))
(lex.add.entry '(T_EH_L nil (((t eh l) 0))
(lex.add.entry '(K_AY_N nil (((k ay n) 0))
(lex.add.entry '(K_AY_L nil (((k ay l) 0))
